ZZRGUT5 ;RGI/VSL - Unit Tests - Problem List ;4/24/12
 ;;1.0;UNIT TEST;;Apr 25, 2012;Build 1;
 S IO=""
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZRGUT5")
 Q
 ;
STARTUP ;
 TSTART
 S DUZ=1,DUZ(0)="@",IO="",U="^"
 S DT=$P($$HTFM^XLFDT($H),".")
 S GMPDFN=1
 S GMPROV=1
 D GETPRB(.GMPPRB)
 S PROB=$$NEW^GMPLAPI2(.RETURN,GMPDFN,GMPROV,.GMPPRB)
 S PROB=RETURN
 D UPDPROB
 Q
 ;
SETUP ;
 Q
 ;
SHUTDOWN ;
 TROLLBACK
 Q
 ;
GETPRB(GMPPRB) ;
 S GMPPRB(.01)="872^253.2"
 S GMPPRB(.05)="^Hypopituitarism (Diabetes Insipidus)"
 S GMPPRB(.08)=DT
 S GMPPRB(.12)="A^ACTIVE"
 S GMPPRB(.13)=DT
 S GMPPRB(1.01)="304837^Hypopituitarism (Diabetes Insipidus)"
 S GMPPRB(1.02)="P"
 S GMPPRB(1.03)=1
 S GMPPRB(1.04)="1^TESTMASTER,USER"
 S GMPPRB(1.05)="1^TESTMASTER,USER"
 S GMPPRB(1.06)="" ; Service
 S GMPPRB(1.07)=DT ; Date resolved
 S GMPPRB(1.08)="1"
 S GMPPRB(1.09)=DT
 S GMPPRB(1.1)="0^NO"
 S GMPPRB(1.11)="0^NO"
 S GMPPRB(1.12)="0^NO"
 S GMPPRB(1.13)="0^NO"
 S GMPPRB(1.14)="A^ACUTE"
 S GMPPRB(10,0)=0
 S GMPPRB(10,"NEW",1)="TEST COMMENT"
 Q
 ;
GETHIST ;
 N HIST,AUDIT
 D GETHIST^GMPLHIST(.HIST,PROB)
 S AID=0
 F  S AID=$O(HIST(AID)) Q:AID'>0  D
 . K AUDIT D AUDET^GMPLHIST(.AUDIT,HIST(AID))
 . S ITEM=^GMPL(125.8,HIST(AID),0)
 . S FLD=$P(ITEM,U,2)
 . D CHKEQ^XTMUNIT(AUDIT("DATE"),$$EXTDT^GMPLX($P(ITEM,U,3)),"Invalid audit date - "_FLD)
 . D CHKEQ^XTMUNIT(AUDIT("FLD"),FLD_U_$$FLDNAME^GMPLHIST(FLD),"Invalid audit field - "_FLD)
 . D CHKEQ^XTMUNIT(AUDIT("OLD"),$$OLDVAL(FLD,$P(ITEM,U,5)),"Invalid old value - "_FLD)
 . D CHKEQ^XTMUNIT(AUDIT("NEW"),$$NEWVAL(FLD,$P(ITEM,U,6)),"Invalid new value - "_FLD)
 . D CHKEQ^XTMUNIT(AUDIT("PROV"),"TESTMASTER,USER","Invalid provider - "_FLD)
 . Q:$D(^GMPL(125.8,HIST(AID),1))'>0!('$G(AUDIT("OLDDATE")))
 . S ITEM=^GMPL(125.8,HIST(AID),1)
 . D CHKEQ^XTMUNIT(AUDIT("OLDDATE"),$$EXTDT^GMPLX($P(ITEM,U,5)),"Invalid note date - "_FLD)
 . D CHKEQ^XTMUNIT(AUDIT("OLDNOTE"),$P(ITEM,U,3),"Invalid old note - "_FLD)
 Q
 ;
OLDVAL(FLD,VAL) ;
 S OLD(.01)="253.2",OLD(.13)=DT,OLD(1.07)=DT,OLD(.05)="Hypopituitarism (Diabetes Insipidus)"
 S OLD(1.01)="Hypopituitarism (Diabetes Insipidus)",OLD(1.04)="1^TESTMASTER,USER"
 S OLD(1.05)="TESTMASTER,USER",OLD(1.06)="",OLD(1.08)="LAB DIV 050 OOS ID 108",OLD(1101)="C"
 I $D(OLD(FLD)) S VAL=OLD(FLD)
 I (FLD=.13)!(FLD=1.07) S VAL=$$EXTDT^GMPLX(VAL)
 Q VAL
 ;
NEWVAL(FLD,VAL) ;
 S NVAL(.01)="253.1",NVAL(.13)=DT+1,NVAL(1.07)=DT+1,NVAL(.05)="Diabetes Insipidus"
 S NVAL(1.01)="Hyperpituitarism (Acromegaly or Gigantism)",NVAL(1.04)="1^TESTMASTER,USER"
 S NVAL(1.05)="TEST,USER TWO",NVAL(1.06)="IRM",NVAL(1.08)="SECURE MESSAGING",NVAL(1101)=""
 I $D(NVAL(FLD)) S VAL=NVAL(FLD)
 I (FLD=.13)!(FLD=1.07) S VAL=$$EXTDT^GMPLX(VAL)
 Q VAL
 ;
 ;GETHIST1 ;
 ;N HIST,AUDIT
 ;D GETHIST^GMPLHIST(.HIST,PROB)
 ;S AID=0
 ;F  S AID=$O(HIST(AID)) Q:AID'>0  D
 ;. K AUDIT D AUDET^GMPLHIST(.AUDIT,HIST(AID))
 ;. W !
 ;. ZW AUDIT
 ;Q
 ;
UPDPROB ;
 N GMPPRB
 D DETAIL^GMPLAPI2(.GMPPRB,PROB,DUZ,GMPROV)
 M GMPFLD=GMPPRB S GMPFLD(1.09)=DT
 ;
 S GMPFLD(.01)="871^253.1"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(.05)="^Diabetes Insipidus"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(.13)=DT+1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.01)="304836"
 S GMPPRB(1.01)="304837"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.02)="P"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.05)=2
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.06)="1"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.07)=DT+1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.08)=2
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.09)=DT+1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.1)=1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.11)=1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.12)=1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.13)=1
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(1.14)="C"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S $P(GMPFLD(10,1),U,3)="NEW TEST COMMENT"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 ;
 S GMPFLD(.12)="I"
 D UPDATE^GMPLAPI2(.RET,PROB,.GMPPRB,.GMPFLD,DUZ,GMPROV) M GMPFLD=GMPPRB
 Q
 ;
XTENT ;
 ;;GETHIST;Get audit data
 Q
