ZZRGUT2 ;RGI/VSL - Unit Tests - Problem List ;4/24/12
 ;;1.0;UNIT TEST;;Apr 25, 2012;Build 1;
 S IO=""
 I $T(EN^XTMUNIT)'="" D EN^XTMUNIT("ZZRGUT2")
 Q
 ;
STARTUP ;
 TSTART
 S DUZ=1,DUZ(0)="@",IO="",U="^"
 S DT=$P($$HTFM^XLFDT($H),".")
 S ORIGINAL=^GMPL(125.99,1,0)
 Q
 ;
SETUP ;
 Q
 ;
SHUTDOWN ;
 TROLLBACK
 Q
 ;
LOCALCHK(INPUT) ;
 N OUTPUT,RETURN
 D SET^GMPLSITE(.RETURN,.INPUT)
 D GET^GMPLSITE(.OUTPUT)
 D CHKEQ^XTMUNIT(INPUT("VER"),OUTPUT("VER"),"VERIFY INCORRECT")
 D CHKEQ^XTMUNIT(INPUT("PRT"),OUTPUT("PRT"),"PROMPT FOR CHAR INCORRECT")
 D CHKEQ^XTMUNIT(INPUT("CLU"),OUTPUT("CLU"),"USE CLINICAL LEXICON INCORRECT")
 D CHKEQ^XTMUNIT(INPUT("REV"),OUTPUT("REV"),"DISPLAY ORDER INCORRECT")
 D CHKEQ^XTMUNIT(INPUT("SDP"),OUTPUT("SDP"),"SCREEN DUPLICATE ENTRIES INCORRECT")
 Q
 ;
TEST1 ; Test New list
 ;
 N INPUT
 S INPUT("VER")=0
 S INPUT("PRT")=1
 S INPUT("CLU")=0
 S INPUT("REV")=1
 S INPUT("SDP")=0
 D LOCALCHK(.INPUT)
 Q
 ;
TEST2 ; Test New list
 ;
 N INPUT
 S INPUT("VER")=1
 S INPUT("PRT")=0
 S INPUT("CLU")=1
 S INPUT("REV")=0
 S INPUT("SDP")=1
 D LOCALCHK(.INPUT)
 Q
 ;
TEST3 ; Test New list
 ;
 N INPUT,RETURN,ERR
 S INPUT("VE")=1
 S INPUT("PRT")=0
 S ERR=$$SET^GMPLSITE(.RETURN,.INPUT)
 D CHKTF^XTMUNIT('ERR,"ERROR MESSAGE")
 Q
 ;
XTENT ;
 ;;TEST1;Value set 1
 ;;TEST2;Value set 2
 ;;TEST1;Value set 1 repeat
 ;;TEST3;Error
 Q
