#!/usr/bin/env bash
#---------------------------------------------------------------------------
# Copyright 2011-2012 The Open Source Electronic Health Record Agent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#---------------------------------------------------------------------------

# init script for ewdjs

# Debian LSB info
### BEGIN INIT INFO
# Provides:          foiavista-ewdjs
# Required-Start:    $remote_fs $syslog $foiavista
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start EWD.js for VistA at boot time
# Description:       Starts/Stops EWD.js services for VistA.
### END INIT INFO

# Make sure we are root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Setup environment variables
# This path will be replaced with the correct $basedir when a VistA instance
# is created. This script will need to have it hardcoded
source /home/foia/etc/env
export PATH=$PATH:/usr/local/bin

# Start EWD.js background tasks
start() {
    # Start EWD.js
    echo "Starting EWD.js"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/etc/env && nvm use $nodever && daemon --name ewdjs-${instance} -O $basedir/log/ewdjs.log -E $basedir/log/ewdjsErr.log --chdir $basedir/ewdjs node ewdStart-gtm.js OSEHRA-Config"
    echo "Starting EWD.js Rest Server"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/etc/env && nvm use $nodever && cd $basedir/ewdjs && daemon --name ewdRest-${instance} -O $basedir/log/ewdRestOut.log -E $basedir/log/ewdRestErr.log node $basedir/ewdjs/ewdRest.js"
    echo "Starting EWD VistA Term Server"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/etc/env && nvm use $nodever && cd $basedir/ewdjs && daemon --name ewdVistATerm-${instance} -O $basedir/log/ewdVistATermOut.log -E $basedir/log/ewdVistATermErr.log node $basedir/ewdjs/VistATerm.js"
}

# Stop EWD.js background tasks
stop() {
    # Stop EWD.js
    echo "Stopping EWD.js"
    curl "https://127.0.0.1:8080/ewdjsMgr?password=keepThisSecret%21&exit=true" -k
    echo "Stopping EWD.js Rest Server"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/etc/env && nvm use $nodever && daemon --name ewdRest-${instance} --stop"
    echo "Stopping EWD VistA Term Server"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/etc/env && nvm use $nodever && daemon --name ewdVistATerm-${instance} --stop"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 5
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
