// Although this unit has been autogenerated, it is intended to be modified.
// Source uPtInfoData, Date: 5/1/2024 10:51:34 AM

unit uPtInfoCore;

{$RTTI EXPLICIT METHODS([vcProtected, vcPublic, vcPublished])}

interface

uses
  System.Classes,
  System.Generics.Collections,
  System.JSON,
  System.JSON.Serializers,
  Vcl.ComCtrls,
  Vcl.Controls,
  Vcl.ExtCtrls,
  Vcl.Forms,
  Vcl.Graphics,
  Vcl.StdCtrls,
  Vcl.WinXCtrls,
  Winapi.Messages,
  ORCtrls,
  ORFn,
  ORSymbolLabel,
  uPtInfoCommon,
  uPtInfoData,
  VA508AccessibilityManager,
  VA508AccessibilityRouter,
  fBase508Form,
  fHTMLDialog;

type
  TPtInfoRequiredData = class;
  TPtInfoPresentation = class;
  TPtInfoSection = class;
  TPtInfoData = class;

  TPtInfoDataValue = class(TPersistent)
  private
    FDataType: TPtInfoDataTypes.TDataType;
    FFieldType: TPtInfoDataTypes.TFieldType;
    FOwnerPtInfoRequiredData: TPtInfoRequiredData;
    FRequiredType: TPtInfoDataTypes.TRequiredType;
  public
    constructor Create(AOwnerPtInfoRequiredData: TPtInfoRequiredData;
      ARequiredType: TPtInfoDataTypes.TRequiredType;
      ADataType: TPtInfoDataTypes.TDataType;
      AFieldType: TPtInfoDataTypes.TFieldType);
    property DataType: TPtInfoDataTypes.TDataType read FDataType;
    property FieldType: TPtInfoDataTypes.TFieldType read FFieldType;
    property OwnerPtInfoRequiredData: TPtInfoRequiredData
      read FOwnerPtInfoRequiredData;
    property RequiredType: TPtInfoDataTypes.TRequiredType read FRequiredType;
  end;

  TPtInfoDataValues = TObjectList<TPtInfoDataValue>;

  TPtInfoReturnData = class(TReturnData)
  private
    FOwnerPtInfoRequiredData: TPtInfoRequiredData;
    function GetRequiredType: TPtInfoDataTypes.TRequiredType;
    function GetFieldType: TPtInfoDataTypes.TFieldType;
  protected
    procedure PopulateOwner(AOwner: TPtInfoRequiredData);
  public
    property FieldType: TPtInfoDataTypes.TFieldType read GetFieldType;
    property OwnerPtInfoRequiredData: TPtInfoRequiredData
      read FOwnerPtInfoRequiredData;
    property RequiredType: TPtInfoDataTypes.TRequiredType read GetRequiredType;
  end;

  TPtInfoRequiredData = class(TRequiredData)
  private
    FOptionalCount: Integer;
    FOptionalFound: Boolean;
    FOwnerPtInfoPresentation: TPtInfoPresentation;
    FPtInfoReturnData: TObjectList<TPtInfoReturnData>;
    function GetDataType: TPtInfoDataTypes.TDataType;
  protected
    procedure PopulateOwner(AOwner: TPtInfoPresentation);
  public
    constructor Create;
    destructor Destroy; override;
    property DataType: TPtInfoDataTypes.TDataType read GetDataType;
    property OptionalCount: Integer read FOptionalCount write FOptionalCount;
    property OptionalFound: Boolean read FOptionalFound write FOptionalFound;
    property OwnerPtInfoPresentation: TPtInfoPresentation
      read FOwnerPtInfoPresentation;
    property ReturnData: TObjectList<TPtInfoReturnData> read FPtInfoReturnData;
  end;

  TPtInfoGeneralParameters = class(TGeneralParameters)
  private
    FOwnerPtInfoData: TPtInfoData;
    function GetDefaultColorValue: TColor;
    function GetPanelTextAlignmentType: TAlignment;
    function GetPanelPlacement: TSplitViewPlacement;
  protected
    procedure PopulateOwner(AOwner: TPtInfoData);
  public
    property DefaultColorValue: TColor read GetDefaultColorValue;
    property OwnerPtInfoData: TPtInfoData read FOwnerPtInfoData;
    property PanelPlacement: TSplitViewPlacement read GetPanelPlacement;
    property PanelTextAlignmentType: TAlignment read GetPanelTextAlignmentType;
  end;

  TPtInfoLink = class(TObject)
  private
    FControl: TWinControl;
    FGridPanel: TGridPanel;
    FPtInfoData: TPtInfoData;
    FPresentation: TPtInfoPresentation;
    FSection: TPtInfoSection;
    FSectionPanel: Boolean;
    function GetImageIcon: string;
    function GetSection: TPtInfoSection;
  public
    constructor Create(AControl: TWinControl; ASection: TPtInfoSection;
      APresentation: TPtInfoPresentation; AGridPanel: TGridPanel);
    destructor Destroy; override;
    procedure OrphanControl;
    function LinkScreenReaderText(hasExpandImage: boolean): string;
    property Control: TWinControl read FControl;
    property GridPanel: TGridPanel read FGridPanel;
    property ImageIcon: string read GetImageIcon;
    property PtInfoData: TPtInfoData read FPtInfoData;
    property Presentation: TPtInfoPresentation read FPresentation;
    property Section: TPtInfoSection read GetSection;
    property SectionPanel: Boolean read FSectionPanel;
  end;

  TPtInfoPanel = class(TKeyClickPanel)
  private
    FExpandImage: TImage;
    FPtInfoLink: TPtInfoLink;
    FLabel: TLabel;
    FLongText: string;
    FShortText: string;
    FSymbolLabel: TORSymbolLabel;
    FSymbolImage: TImage;
    function GetFontSize: Integer;
    function GetOnClick: TNotifyEvent;
    procedure PanelResize(Sender: TObject);
    procedure RealignImages;
    procedure SetFontSize(const Value: Integer);
    procedure SetOnClick(const Value: TNotifyEvent);
    procedure WMEraseBkgnd(var Message: TWMEraseBkgnd); message WM_ERASEBKGND;
  public
    constructor Create(ASection: TPtInfoSection;
      APresentation: TPtInfoPresentation; AGridPanel: TGridPanel); reintroduce;
    destructor Destroy; override;
    procedure ResetPanelText(UseLongText: Boolean);
    property ExpandImage: TImage read FExpandImage write FExpandImage;
    property FontSize: Integer read GetFontSize write SetFontSize;
    property PtInfoLink: TPtInfoLink read FPtInfoLink;
    property LongText: string read FLongText;
    property ShortText: string read FShortText;
    property SymbolLabel: TORSymbolLabel read FSymbolLabel;
    property SymbolImage: TImage read FSymbolImage write FSymbolImage;
    property TextLabel: TLabel read FLabel;
  published
    property OnClick: TNotifyEvent read GetOnClick write SetOnClick;
  end;

  TPtInfoPresentation = class(TPresentation)
  private
    FDialog: TForm;
    FItemPanel: TPtInfoPanel;
    FOwnerPtInfoData: TPtInfoData;
    FPtInfoRequiredData: TObjectList<TPtInfoRequiredData>;
    FSection: TPtInfoSection;
    procedure CreateHTMLForm(JSON: TJSONValue; Caption: string);
    procedure EditorDateBoxOpening(Sender: TObject);
    procedure EditorDateBoxClosed(Sender: TObject);
    function GetActionType: TPtInfoDataTypes.TActionType;
    function GetColor: string;
    function GetColorValue: TColor;
    function GetDetailsForm: TForm;
    function GetImageIcon: string;
    function GetSection: TPtInfoSection;
    function GetPopOutType: TPtInfoDataTypes.TPopOutType;
    procedure HTMLDialogCloseQuery(Sender: TfrmHTMLDialog; Content: TJSONObject;
      Canceling: Boolean; var CanClose: Boolean);
    procedure HTMLDialogSubmit(Sender: TfrmHTMLDialog; Content: TJSONObject);
    function IsDataValid: Boolean;
    procedure FormatForURLs(ARichEdit: TRichEdit);
    procedure PanelClick(Sender: TObject);
    procedure PanelShowDetail(Sender: TObject; AForm: TForm; JSON: TJSONValue;
      Update: Boolean);
    procedure PanelShowURL(Sender: TObject; AForm: TForm; JSON: TJSONValue;
      Update: Boolean);
    procedure PanelShowMessage(Sender: TObject; JSON: TJSONValue;
      Update: Boolean);
    procedure PanelShowEditor(Sender: TObject; AForm: TForm; JSON: TJSONValue;
      Update: Boolean);
    function RetrieveValue(ADataType: TPtInfoDataTypes.TDataType;
      AFieldType: TPtInfoDataTypes.TFieldType): string;
    procedure SetColor(const Value: string);
    procedure SetImageIcon(const Value: string);
    procedure resetFocus;
  protected
    procedure PopulateOwner(AOwner: TPtInfoData);
  public
    constructor Create;
    destructor Destroy; override;
    function ShouldDisplayPanel(PageID: Integer): Boolean;
    procedure CloseDetailsForm;
    procedure CloseEmbeddedForm(AForm: TForm);
    function DataToJSON: TJSONObject;
    procedure OrphanPanels;
    procedure ResetFont;
    procedure ResetPanelText(UseLongText: Boolean);
    procedure RetrieveMissingData(MissingData: TPtInfoDataValues);
    procedure SetupPanels(ARowHeight: Integer);
    property ActionType: TPtInfoDataTypes.TActionType read GetActionType;
    property Color: string read GetColor write SetColor;
    property ColorValue: TColor read GetColorValue;
    property Dialog: TForm read FDialog;
    property ImageIcon: string read GetImageIcon write SetImageIcon;
    property OwnerPtInfoData: TPtInfoData read FOwnerPtInfoData;
    property PopOutType: TPtInfoDataTypes.TPopOutType read GetPopOutType;
    property Section: TPtInfoSection read GetSection;
    property RequiredData: TObjectList<TPtInfoRequiredData>
      read FPtInfoRequiredData;
    property ItemPanel: TPtInfoPanel read FItemPanel write FItemPanel;
  end;

  TPtInfoSection = class(TSection)
  private
    FCollapsed: Boolean;
    FImageWidth: Integer;
    FImageWidthCalcNeeded: Boolean;
    FOwnerPtInfoData: TPtInfoData;
    FSectionPanel: TPtInfoPanel;
    FUsed: Boolean;
    FClicked: boolean;
    function CalcImageWidth(ImageData: string): Integer;
    function GetColor: string;
    function GetColorValue: TColor;
    function GetHasImages: Boolean;
    function GetImageIcon: string;
    function GetImageWidth: Integer;
    procedure PanelClick(Sender: TObject);
    procedure SetColor(const Value: string);
    procedure SetImageIcon(const Value: string);
  protected
    procedure PopulateOwner(AOwner: TPtInfoData);
  public
    procedure OrphanPanels;
    procedure ResetFont;
    procedure ResetPanelText(UseLongText: Boolean);
    procedure SetupSection(ARowHeight: Integer);
    property Collapsed: Boolean read FCollapsed write FCollapsed;
    property Color: string read GetColor write SetColor;
    property ColorValue: TColor read GetColorValue;
    property HasImages: Boolean read GetHasImages;
    property ImageIcon: string read GetImageIcon write SetImageIcon;
    property ImageWidth: Integer read GetImageWidth;
    property OwnerPtInfoData: TPtInfoData read FOwnerPtInfoData;
    property Used: Boolean read FUsed write FUsed;
  end;

  TPtInfoSaveResults = class;

  TPtInfoNoteInfo = class(TObject)
  private
    FDateTime: TFMDateTime;
    FDetails: string;
    FID: Integer;
    FTitle: string;
  public
    property DateTime: TFMDateTime read FDateTime write FDateTime;
    property Details: string read FDetails write FDetails;
    property ID: Integer read FID write FID;
    property Title: string read FTitle write FTitle;
  end;

  TPtInfoSaveResults = class(TObject)
  private
    FPtInfoNoteInfo: TPtInfoNoteInfo;
    FRefreshAllInfoPanels: Boolean;
    FSuccess: Boolean;
  public
    constructor Create;
    destructor Destroy; override;
  public
    property NoteInformation: TPtInfoNoteInfo read FPtInfoNoteInfo
      write FPtInfoNoteInfo;
    property RefreshAllInfoPanels: Boolean read FRefreshAllInfoPanels
      write FRefreshAllInfoPanels;
    property Success: Boolean read FSuccess write FSuccess;
  end;

  TPtInfoData = class(TData)
  private
    FHTMLDialogIDs: TStringList;
    FOwnerPtInfoSplitViewBase: TPtInfoSplitViewBase;
    FPtInfoGeneralParameters: TPtInfoGeneralParameters;
    FPtInfoPresentation: TObjectList<TPtInfoPresentation>;
    FPtInfoSections: TObjectList<TPtInfoSection>;
    FResetPanels: Boolean;
    FRowHeight: Integer;
    function GetCurrentEmbeddedPresentation: TPtInfoPresentation;
    function GetHasImages: Boolean;
  protected
    procedure HTMLDialogCreate(ID: string);
    class function IsImageIconSymbol(ImageData: string): Boolean;
    procedure PopulateOwner(AOwner: TPtInfoSplitViewBase);
  public
    constructor Create;
    destructor Destroy; override;
    procedure AdjustPanels;
    procedure CloseAllDetails;
    procedure CloseEmbeddedDetails(AForm: TForm);
    procedure ResetFont(ARowHeight: Integer);
    procedure ResetPanelText(UseLongText: Boolean);
    function SetupPanels(PageID: Integer; ARowHeight: Integer): Boolean;
    property CurrentEmbeddedPresentation: TPtInfoPresentation
      read GetCurrentEmbeddedPresentation;
    property GeneralParameters: TPtInfoGeneralParameters
      read FPtInfoGeneralParameters;
    property HasImages: Boolean read GetHasImages;
    property OwnerPtInfoSplitViewBase: TPtInfoSplitViewBase
      read FOwnerPtInfoSplitViewBase;
    property Presentation: TObjectList<TPtInfoPresentation>
      read FPtInfoPresentation;
    property ResetPanels: Boolean read FResetPanels write FResetPanels;
    property RowHeight: Integer read FRowHeight;
    property Sections: TObjectList<TPtInfoSection> read FPtInfoSections;
  end;

  TPtInfoDataConverter = class(TObject)
  private
    class function InternalToObject<T, U: class>(JSONValue: TJSONValue; JSONString: string; AOwner: U): T;
    class function LibraryName: string;
  public
    class function ToJSON<T>(AObject: T): string;
    class function ToObject<T, U: class>(JSON: TJSONValue; AOwner: U): T; overload;
    class function ToObject<T, U: class>(JSON: string; AOwner: U): T; overload;
    class function ToObject<T: class>(JSON: string): T; overload;
    class function ToObject<T: class>(JSON: TJSONValue): T; overload;
  end;

implementation

uses
  System.SysUtils,
  System.Types,
  System.JSON.Converters,
  System.JSON.Writers,
  System.JSON.Readers,
  System.Rtti,
  System.TypInfo,
  Winapi.RichEdit,
  Winapi.ShellAPI,
  Winapi.Windows,
  ORDtTm,
  ORNet,
  VAShared.RttiUtils,
  VAShared.UJSONValueHelper,
  VAUtils,
  fRptBox,
  rMisc,
  fFrame,
  fPtInfoDetails,
  fEncnt,
  uConst,
  rPtInfo,
  uCore,
  uPCE,
  uMisc;

var
  PtInfoDataJSONLibrary: string;
  PtInfoDataJSONSerializerRegistered: Boolean = False;

procedure FreeAndNilOld(ATypeInf: PTypeInfo; Instance: TObject;
  FieldName: string);
var
  LField: TRttiField;
begin
  LField := TRttiUtils.GetRttiField(ATypeInf, FieldName);
  if Assigned(LField) then
  begin
    LField.GetValue(Instance).AsObject.Free;
    LField.SetValue(Instance, nil);
  end;
end;

{ TDataValue }

constructor TPtInfoDataValue.Create(AOwnerPtInfoRequiredData
  : TPtInfoRequiredData; ARequiredType: TPtInfoDataTypes.TRequiredType;
  ADataType: TPtInfoDataTypes.TDataType;
  AFieldType: TPtInfoDataTypes.TFieldType);
begin
  inherited Create;
  FOwnerPtInfoRequiredData := AOwnerPtInfoRequiredData;
  FRequiredType := ARequiredType;
  FDataType := ADataType;
  FFieldType := AFieldType;
end;

{ TPtInfoReturnData }

function TPtInfoReturnData.GetFieldType: TPtInfoDataTypes.TFieldType;
begin
  Result := TRttiUtils.GetEnumValueFromString<TPtInfoDataTypes.TFieldType>
    (dataName, 'fld');
end;

function TPtInfoReturnData.GetRequiredType: TPtInfoDataTypes.TRequiredType;
begin
  Result := TRttiUtils.GetEnumValueFromString<TPtInfoDataTypes.TRequiredType>
    (required, 'req');
end;

procedure TPtInfoReturnData.PopulateOwner(AOwner: TPtInfoRequiredData);
begin
  FOwnerPtInfoRequiredData := AOwner;
end;

{ TPtInfoRequiredData }

constructor TPtInfoRequiredData.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TObjectList<TReturnData>), Self, 'FReturnData');
  FPtInfoReturnData := TObjectList<TPtInfoReturnData>.Create(True);
end;

destructor TPtInfoRequiredData.Destroy;
begin
  FreeAndNil(FPtInfoReturnData);
  inherited;
end;

function TPtInfoRequiredData.GetDataType: TPtInfoDataTypes.TDataType;
begin
  Result := TRttiUtils.GetEnumValueFromString<TPtInfoDataTypes.TDataType>
    (dataName);
end;

procedure TPtInfoRequiredData.PopulateOwner(AOwner: TPtInfoPresentation);
begin
  FOwnerPtInfoPresentation := AOwner;
  for var I := 0 to FPtInfoReturnData.Count - 1 do
    FPtInfoReturnData[I].PopulateOwner(Self);
end;

{ TPtInfoGeneralParameters }

function TPtInfoGeneralParameters.GetDefaultColorValue: TColor;
begin
  if colorEnabled and (defaultColor <> '') then
    Result := StringToColor(defaultColor)
  else
    Result := TPtInfoDataTypes.MainDefaultColorValue;
end;

function TPtInfoGeneralParameters.GetPanelPlacement: TSplitViewPlacement;
begin
  Result := TRttiUtils.GetEnumValueFromString<TSplitViewPlacement>
    (panelAlignment);
end;

function TPtInfoGeneralParameters.GetPanelTextAlignmentType: TAlignment;
begin
  Result := TRttiUtils.GetEnumValueFromString<TAlignment>(panelTextAlignment);
end;

procedure TPtInfoGeneralParameters.PopulateOwner(AOwner: TPtInfoData);
begin
  FOwnerPtInfoData := AOwner;
end;

{ TPtInfoLink }

constructor TPtInfoLink.Create(AControl: TWinControl; ASection: TPtInfoSection;
  APresentation: TPtInfoPresentation; AGridPanel: TGridPanel);
begin
  inherited Create;
  FControl := AControl;
  FSection := ASection;
  FPresentation := APresentation;
  FGridPanel := AGridPanel;
  FSectionPanel := Assigned(FSection);
  if (not Assigned(FSection)) and Assigned(FPresentation) and
    Assigned(FPresentation.Section) then
    FSection := FPresentation.Section;
  if Assigned(FSection) then
    FPtInfoData := FSection.OwnerPtInfoData
  else if Assigned(FPresentation) then
    FPtInfoData := FPresentation.OwnerPtInfoData;
end;

destructor TPtInfoLink.Destroy;
begin
  OrphanControl;
  inherited;
end;

function TPtInfoLink.GetImageIcon: string;
begin
  Result := '';
  if SectionPanel then
  begin
    if Assigned(Section) then
      Result := Section.ImageIcon;
  end
  else if Assigned(Presentation) then
    Result := Presentation.ImageIcon;
end;

function TPtInfoLink.GetSection: TPtInfoSection;
begin
  if (not Assigned(FSection)) and Assigned(FPresentation) and
    Assigned(FPresentation.Section) then
    FSection := FPresentation.Section;
  Result := FSection;
end;

function TPtInfoLink.LinkScreenReaderText(hasExpandImage: boolean): string;
begin
  result := 'Unknown Information Panel';
  if SectionPanel then
  begin
    if hasExpandImage then
    begin
      if Section.FCollapsed then result := 'press spacebar to expand section'
      else result := 'press spacebar to collapse section';
    end
    else result := 'Section Header';
  end;
  if Assigned(Presentation) then
  begin
    if Presentation.GetActionType = actNone then result := 'Information Only'
    else if (Presentation.GetActionType = actShowDetail) or
            (Presentation.GetActionType = actShowMessage) then
      result := ' press space bar to view additional information'
    else if (Presentation.GetActionType = actShowEditor) or
            (Presentation.GetActionType = actShowHTMLEditor) then
      result := ' press space bar to update record'
    else if Presentation.GetActionType = actShowURL then result := 'press space to view more information in a broswer';
  end;
end;

procedure TPtInfoLink.OrphanControl;
begin
  FControl.Visible := False;
  FControl.Align := alNone;
  FControl.Parent := nil;
  if Assigned(FGridPanel) then
    FGridPanel.ControlCollection.RemoveControl(FControl);
end;

{ TPtInfoPanel }

type
  TBitmapAccess = class(Vcl.Graphics.TBitmap);

constructor TPtInfoPanel.Create(ASection: TPtInfoSection;
  APresentation: TPtInfoPresentation; AGridPanel: TGridPanel);
const
  InvaldImageError = '59961;clWindowText;60304;clRed';

var
  ImageData: string;

  procedure CreateLabel;
  begin
    FLabel := TLabel.Create(Self);
    FLabel.Parent := Self;
    FLabel.Align := alClient;
    FLabel.AlignWithMargins := True;
    FLabel.Margins.Top := 0;
    FLabel.Margins.Bottom := 0;
    FLabel.Margins.Left := TPtInfoDataTypes.LabelMarginSize;
    FLabel.Margins.Right := TPtInfoDataTypes.LabelMarginSize;
    FLabel.Alignment := Alignment;
    FLabel.Layout := tlCenter;
  end;

  procedure CreateExpandImage;
  begin
    if Assigned(ASection) and ASection.Collapsible then
    begin
      FExpandImage := TImage.Create(Self);
      FExpandImage.Parent := Self;
      if Alignment = taRightJustify then
      begin
        FExpandImage.Align := alRight;
        FExpandImage.Margins.Left := 0;
        FExpandImage.Margins.Right := TPtInfoDataTypes.LabelMarginSize;
      end
      else
      begin
        FExpandImage.Align := alLeft;
        FExpandImage.Margins.Left := TPtInfoDataTypes.LabelMarginSize;
        FExpandImage.Margins.Right := 0;
      end;
      FExpandImage.AlignWithMargins := True;
      FExpandImage.Margins.Top := 0;
      FExpandImage.Margins.Bottom := 0;
      FExpandImage.Center := True;
      FExpandImage.Transparent := True;
      if ASection.Collapsed then
        FExpandImage.Picture.Assign
          (FPtInfoLink.PtInfoData.OwnerPtInfoSplitViewBase.ImageExpand.Picture)
      else
        FExpandImage.Picture.Assign
          (FPtInfoLink.PtInfoData.OwnerPtInfoSplitViewBase.
          ImageCollapse.Picture);
      FExpandImage.Width := FPtInfoLink.PtInfoData.OwnerPtInfoSplitViewBase.
        ImageExpand.Width;
    end;
  end;

  procedure CreateSymbolLabel;
  begin
    FSymbolLabel := TORSymbolLabel.Create(Self);
    FSymbolLabel.Parent := Self;
    FSymbolLabel.AlignWithMargins := True;
    FSymbolLabel.Margins.Top := 0;
    FSymbolLabel.Margins.Bottom := 0;
    if Alignment = taRightJustify then
      FSymbolLabel.Align := alRight
    else
      FSymbolLabel.Align := alLeft;
    FSymbolLabel.Alignment := taCenter;
    FSymbolLabel.Layout := tlCenter;
    FSymbolLabel.Symbol.FromString(ImageData);
  end;

  procedure CreateImageIcon;
  var
    Panel: TPanel;
    Mem: TMemoryStream;

    function ReadBool: Boolean;
    begin
      Mem.Read(Result, SizeOf(Boolean));
    end;

  begin
    Panel := TPanel.Create(Self);
    Panel.Parent := Self;
    Panel.BevelOuter := bvNone;
    Panel.Caption := '';
    Panel.AlignWithMargins := True;
    if Alignment = taRightJustify then
      Panel.Align := alRight
    else
      Panel.Align := alLeft;
    Panel.Width := Panel.Height;
    Panel.OnResize := PanelResize;
    FSymbolImage := TImage.Create(Self);
    FSymbolImage.Parent := Panel;
    FSymbolImage.Align := alClient;
    Mem := TMemoryStream.Create;
    try
      try
        Mem.Size := Length(ImageData) div 2;
        HexToBin(PWideChar(ImageData), Mem.Memory^, Mem.Size);
        Mem.Position := 0;
        FSymbolImage.Center := ReadBool;
        FSymbolImage.Stretch := ReadBool;
        FSymbolImage.Transparent := ReadBool;
        TBitmapAccess(FSymbolImage.Picture.Bitmap).ReadData(Mem);
      except
        FreeAndNil(FSymbolImage);
        FreeAndNil(Panel);
        ImageData := InvaldImageError;
        if FPtInfoLink.SectionPanel then
          FPtInfoLink.Section.ImageIcon := ImageData
        else
          FPtInfoLink.Presentation.ImageIcon := ImageData;
        CreateSymbolLabel;
      end;
    finally
      Mem.Free;
    end;
  end;

begin
  if (not Assigned(ASection)) and (not Assigned(APresentation)) then
    raise EArgumentException.Create
      ('Can''t create TPtInfoPanel without a valid TPtInfoSection or TPtInfoPresentation.');
  inherited Create(nil);
  FPtInfoLink := TPtInfoLink.Create(Self, ASection, APresentation, AGridPanel);
  Font.Assign(MainFont);
  ParentBackground := False;
  ParentColor := False;
  Caption := '';
  if (not FPtInfoLink.PtInfoData.GeneralParameters.ImageIconEnabled) then
    ImageData := ''
  else
    ImageData := FPtInfoLink.ImageIcon;
  Alignment := FPtInfoLink.PtInfoData.GeneralParameters.PanelTextAlignmentType;
  CreateLabel;
  CreateExpandImage;
  if (ImageData <> '') then
  begin
    if TPtInfoData.IsImageIconSymbol(ImageData) then
      CreateSymbolLabel
    else
      CreateImageIcon;
  end;
//  if ScreenReaderActive then
//  begin
////    (GetParentForm(AGridPanel) as TfrmBase508Form).amgrMain.AccessText[TWinControl(self)] := self.LongText + ' Click to perform action';
//    (GetParentForm(AGridPanel) as TfrmBase508Form).amgrMain.AccessText[self] := self.FLabel.ToString + ' Click to perform action';
//  end;
end;

destructor TPtInfoPanel.Destroy;
begin
  if assigned(FLabel) then FreeAndNil(FLabel);
  if assigned(FExpandImage) then FreeAndNil(FExpandImage);
  if assigned(FSymbolImage) then FreeAndNil(FSymbolImage);

  FreeAndNil(FPtInfoLink);
  inherited;
end;

function TPtInfoPanel.GetFontSize: Integer;
begin
  Result := Font.Size;
end;

function TPtInfoPanel.GetOnClick: TNotifyEvent;
begin
  Result := inherited OnClick;
end;

procedure TPtInfoPanel.PanelResize(Sender: TObject);
begin
  if Sender is TPanel then
    (Sender as TPanel).Width := (Sender as TPanel).Height;
end;

procedure TPtInfoPanel.RealignImages;
var
  TreeOffset, SectionOffset, ImageWidth, Diff, DiffLeft, DiffRight,
    IndentOffset: Integer;
  Panel: TPanel;
  BumpDiff: Boolean;
begin
  if Assigned(FPtInfoLink.Section) and
    ((not FPtInfoLink.SectionPanel) or (FPtInfoLink.Section.ImageIcon <> ''))
  then
    ImageWidth := FPtInfoLink.Section.ImageWidth
  else
    ImageWidth := 0;
  if FPtInfoLink.SectionPanel and (not FPtInfoLink.Section.Collapsible) and
    (Alignment <> taRightJustify) then
    SectionOffset := 1
  else
    SectionOffset := 0;
  if (not FPtInfoLink.SectionPanel) and Assigned(FPtInfoLink.Section) and
    FPtInfoLink.Section.Collapsible then
  begin
    TreeOffset := FPtInfoLink.PtInfoData.OwnerPtInfoSplitViewBase.
      ImageExpand.Width;
    if (FPtInfoLink.Section.ImageIcon <> '') or (ImageWidth = 0) then
      TreeOffset := TreeOffset * 2;
  end
  else
    TreeOffset := 0;
  if (FPtInfoLink.PtInfoData.GeneralParameters.indentText) and
    (FPtInfoLink.PtInfoData.GeneralParameters.PanelTextAlignmentType <>
    taCenter) and (not FPtInfoLink.SectionPanel) and
    Assigned(FPtInfoLink.Section) and (not FPtInfoLink.Section.Collapsible) then
    IndentOffset := FPtInfoLink.PtInfoData.OwnerPtInfoSplitViewBase.
      ImageExpand.Width
  else
    IndentOffset := 0;
  if Assigned(FExpandImage) then
    case Alignment of
      taLeftJustify, taCenter:
        FExpandImage.Left := 0;
      taRightJustify:
        FExpandImage.Left := Width - FExpandImage.Width;
    end;
  if Assigned(FSymbolLabel) then
  begin
    Diff := HigherOf(ImageWidth - FSymbolLabel.Width, 0);
    DiffLeft := (Diff div 2);
    DiffRight := Diff - DiffLeft;
    if Alignment = taRightJustify then
    begin
      FSymbolLabel.Margins.Left := DiffLeft;
      FSymbolLabel.Margins.Right := TPtInfoDataTypes.LabelMarginSize +
        TreeOffset + IndentOffset + DiffRight;
      if Assigned(FExpandImage) then
        FSymbolLabel.Left := 0;
    end
    else
    begin
      FSymbolLabel.Margins.Left := TPtInfoDataTypes.LabelMarginSize + TreeOffset
        + SectionOffset + IndentOffset + DiffLeft;
      FSymbolLabel.Margins.Right := DiffRight;
      if Assigned(FExpandImage) then
        FSymbolLabel.Left := Width;
    end;
  end
  else if Assigned(FSymbolImage) then
  begin
    Panel := FSymbolImage.Parent as TPanel;
    if FPtInfoLink.SectionPanel then
      Diff := 1
    else
      Diff := 0;
    Panel.Margins.Top := TPtInfoDataTypes.ImageMarginSizeTop
      [MainFont.Size] + Diff;
    Panel.Margins.Bottom := TPtInfoDataTypes.ImageMarginSizeBottom
      [MainFont.Size] + Diff;
    if Assigned(FPtInfoLink.Section) and (not FPtInfoLink.SectionPanel) then
    begin
      Diff := FPtInfoLink.Section.CalcImageWidth(FPtInfoLink.ImageIcon);
      Diff := HigherOf(ImageWidth - Diff, 0);
    end
    else
      Diff := 0;
    DiffLeft := (Diff div 2);
    DiffRight := Diff - DiffLeft;
    if Alignment = taRightJustify then
    begin
      Panel.Margins.Left := DiffLeft;
      Panel.Margins.Right := TPtInfoDataTypes.LabelMarginSize + TreeOffset +
        IndentOffset + DiffRight;
    end
    else
    begin
      Panel.Margins.Left := TPtInfoDataTypes.LabelMarginSize + TreeOffset +
        IndentOffset + SectionOffset + DiffLeft;
      Panel.Margins.Right := DiffRight;
      if Assigned(FExpandImage) then
        Panel.Left := Panel.BoundsRect.Right;
    end;
  end
  else
  begin
    Diff := TPtInfoDataTypes.LabelMarginSize + TreeOffset + SectionOffset +
      IndentOffset;
    BumpDiff := (ImageWidth > 0);
    if BumpDiff then
    begin
      BumpDiff := (FPtInfoLink.SectionPanel and (FPtInfoLink.ImageIcon = '') and
        (not FPtInfoLink.Section.Collapsible));
      if not BumpDiff then
        BumpDiff := (not FPtInfoLink.SectionPanel) or (Alignment = taCenter);
    end;
    if BumpDiff then
      inc(Diff, TPtInfoDataTypes.LabelMarginSize + ImageWidth);
    if Alignment = taRightJustify then
      FLabel.Margins.Right := Diff
    else
      FLabel.Margins.Left := Diff;
  end;
end;

procedure TPtInfoPanel.ResetPanelText(UseLongText: Boolean);
begin
  if UseLongText then
    FLabel.Caption := FLongText
  else
    FLabel.Caption := FShortText;
  Hint := FLongText;
  ShowHint := True;
  if ScreenReaderActive then
  begin
//    (GetParentForm(AGridPanel) as TfrmBase508Form).amgrMain.AccessText[TWinControl(self)] := self.LongText + ' Click to perform action';
    (GetParentForm(FPtInfoLink.FGridPanel) as TfrmBase508Form).amgrMain.AccessText[self] := self.FLabel.Caption + FPtInfoLink.LinkScreenReaderText(assigned(ExpandImage));
  end;
end;

procedure TPtInfoPanel.SetFontSize(const Value: Integer);
begin
  Font.Size := Value;
  FLabel.Font.Size := Value;
  if Assigned(FSymbolLabel) then
    FSymbolLabel.Font.Size := Value + TPtInfoDataTypes.SymbolFontOffset;
  RealignImages;
end;

procedure TPtInfoPanel.SetOnClick(const Value: TNotifyEvent);
begin
  inherited OnClick := Value;
  FLabel.OnClick := Value;
  if Assigned(FExpandImage) then
    FExpandImage.OnClick := Value;
  if Assigned(FSymbolLabel) then
    FSymbolLabel.OnClick := Value;
  if Assigned(FSymbolImage) then
    FSymbolImage.OnClick := Value;
end;

// prevents image flickering when resizing Info Panel
procedure TPtInfoPanel.WMEraseBkgnd(var Message: TWMEraseBkgnd);
begin
  Message.Result := 0;
end;

{ TPtInfoPresentation }

procedure TPtInfoPresentation.CloseDetailsForm;
begin
  if Assigned(FDialog) and FDialog.Visible then
    FDialog.Close;
end;

procedure TPtInfoPresentation.CloseEmbeddedForm(AForm: TForm);
begin
  if (PopOutType = popShowEmbedded) and Assigned(FDialog) and
    FDialog.Visible and (FDialog <> AForm) then
    FDialog.Close;
end;

constructor TPtInfoPresentation.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TObjectList<TRequiredData>), Self, 'FRequiredData');
  FPtInfoRequiredData := TObjectList<TPtInfoRequiredData>.Create(True);
end;

function TPtInfoPresentation.DataToJSON: TJSONObject;
var
  Elem, DType, Data: TJSONObject;
  List: TJSONArray;
  Value: string;

begin
  Result := nil;
  if not IsDataValid then
    Exit;
  Result := TJSONObject.Create;
  Result.AddPair('id', panelId);
  if Assigned(Section) and Assigned(Section) then
    Result.AddPair('isNational', Section.IsNational);
  Result.AddPair('patientId', Patient.DFN);
  Result.AddPair('package', VISTA_PACKAGE);
  Result.AddPair('connectionUser', User.DUZ);
  if Assigned(RequiredData) and (RequiredData.Count > 0) then
  begin
    List := TJSONArray.Create;
    Result.AddPair('requiredData', List);
    for var I := 0 to RequiredData.Count - 1 do
    begin
      Elem := TJSONObject.Create;
      List.Add(Elem);
      DType := TJSONObject.Create;
      Elem.AddPair('dataType', DType);
      DType.AddPair('name', RequiredData[I].dataName);
      Data := TJSONObject.Create;
      DType.AddPair('data', Data);
      if Assigned(RequiredData[I].ReturnData) and
        (RequiredData[I].ReturnData.Count > 0) then
        for var j := 0 to RequiredData[I].ReturnData.Count - 1 do
        begin
          Value := RetrieveValue(RequiredData[I].DataType,
            RequiredData[I].ReturnData[j].FieldType);
          Data.AddPair(RequiredData[I].ReturnData[j].dataName, Value);
        end;
    end;
  end;
end;

destructor TPtInfoPresentation.Destroy;
begin
  FreeAndNil(FItemPanel);
  FreeAndNil(FDialog);
  FreeAndNil(FPtInfoRequiredData);
  inherited;
end;

procedure TPtInfoPresentation.EditorDateBoxClosed(Sender: TObject);
begin
  OwnerPtInfoData.OwnerPtInfoSplitViewBase.FloatMonitoring := True;
end;

procedure TPtInfoPresentation.EditorDateBoxOpening(Sender: TObject);
begin
  OwnerPtInfoData.OwnerPtInfoSplitViewBase.FloatMonitoring := False;
end;

procedure TPtInfoPresentation.FormatForURLs(ARichEdit: TRichEdit);
var
  I, j: Integer;
  Line: string;
  Format: TCharFormat2;
begin
  I := SendMessage(ARichEdit.Handle, EM_GETEVENTMASK, 0, 0);
  SendMessage(ARichEdit.Handle, EM_SETEVENTMASK, 0, I or ENM_LINK);
  SendMessage(ARichEdit.Handle, EM_AUTOURLDETECT, Integer(True), 0);
  with ARichEdit do
  begin
    if Lines.Count > 1 then
    begin
      I := 0;
      repeat
        Line := Lines[I];
        j := Length(Line);
        if (j > 0) and (ord(Line[j]) > 32) and (Length(Lines[I + 1]) > 0) and
          (ord(Lines[I + 1][1]) > 32) then
        begin
          CaretPos := Point(j - 1, I);
          SelLength := 1;
          FillChar(Format, SizeOf(TCharFormat2), 0);
          Format.cbSize := SizeOf(TCharFormat2);
          SendGetStructMessage(Handle, EM_GETCHARFORMAT, WPARAM(True),
            Format, True);
          if (Format.dwEffects and CFE_LINK) <> 0 then
          begin
            Line := Line + Lines[I + 1];
            Lines[I] := Line;
            Lines.Delete(I + 1);
            dec(I);
          end;
        end;
        inc(I);
      until I >= (Lines.Count - 1);
    end;
    SelStart := 0;
  end;
end;

function TPtInfoPresentation.GetActionType: TPtInfoDataTypes.TActionType;
begin
  Result := TRttiUtils.
    GetEnumValueFromString<TPtInfoDataTypes.TActionType>(action);
end;

function TPtInfoPresentation.GetColor: string;
begin
  if OwnerPtInfoData.GeneralParameters.colorEnabled then
    Result := inherited Color
  else
    Result := '';
end;

function TPtInfoPresentation.GetColorValue: TColor;
begin
  if OwnerPtInfoData.GeneralParameters.colorEnabled then
  begin
    if Color <> '' then
      Result := StringToColor(Color)
    else
      Result := OwnerPtInfoData.GeneralParameters.DefaultColorValue
  end
  else
    Result := TPtInfoDataTypes.MainDefaultColorValue;
end;

function TPtInfoPresentation.GetDetailsForm: TForm;
var
  Grid: TGridPanel;
  Form: TfrmPtInfoDetails;
begin
  if PopOutType = popShowEmbedded then
    Grid := OwnerPtInfoData.OwnerPtInfoSplitViewBase.FormGrid
  else
    Grid := nil;
  if Assigned(FDialog) then
    Form := FDialog as TfrmPtInfoDetails
  else
  begin
    Form := TfrmPtInfoDetails.Create(Self, Grid);
    FDialog := Form;
  end;
  if Assigned(Grid) then
  begin
    while Grid.ControlCollection.Count > 0 do
      Grid.ControlCollection.RemoveControl(Grid.ControlCollection.Items
        [Grid.ControlCollection.Count - 1].Control);
    Grid.ControlCollection.AddControl(Form, 0, 0);
    Form.Parent := Grid;
    Form.Align := alClient;
    Form.BorderStyle := bsNone;
  end
  else
  begin
    Form.BorderStyle := bsSizeable;
    Form.Caption := DisplayText;
  end;
  Form.pnlHeader.Height := OwnerPtInfoData.RowHeight;
  Form.lblHeader.Caption := DisplayText;
  Result := Form;
end;

procedure TPtInfoPresentation.CreateHTMLForm(JSON: TJSONValue; Caption: string);
var
  Contents: TJSONArray;
  DataObj: TJSONObject;
  WebContentType: TWebContentType;
  Data: Array [wcData .. wcUISchema] of string;
begin
  if (ActionType <> actShowHTMLEditor) or (not Assigned(JSON)) then
    Exit;
  Contents := JSON.AsTypeDef<TJSONArray>('contents', nil);
  if not Assigned(Contents) then
    Exit;
  for Var I := Low(Data) to High(Data) do
    Data[I] := '';
  for var I := 0 to Contents.Count - 1 do
  begin
    WebContentType := TRttiUtils.GetEnumValueFromString<TWebContentType>
      (Contents[I].AsTypeDef<string>('contentType', ''), 'wc');
    case WebContentType of
      wcData, wcSchema, wcUISchema:
        begin
          DataObj := Contents[I].AsTypeDef<TJSONObject>('data', nil);;
          if Assigned(DataObj) then
            Data[WebContentType] := DataObj.ToString;
        end;
    end;
  end;
  if Data[wcSchema] <> '' then
  begin
    CreateHTMLDialog(TfrmHTMLDialog.TParams.Create
      (PopOutType = popShowModal, '', HTMLDialogSubmit, nil,
      HTMLDialogCloseQuery, Data[wcSchema], Data[wcUISchema], Data[wcData],
      panelId, caption));

  end;
end;

function TPtInfoPresentation.GetImageIcon: string;
begin
  if OwnerPtInfoData.GeneralParameters.ImageIconEnabled then
    Result := inherited ImageIcon
  else
    Result := '';
end;

function TPtInfoPresentation.GetPopOutType: TPtInfoDataTypes.TPopOutType;
begin
  Result := TRttiUtils.GetEnumValueFromString<TPtInfoDataTypes.TPopOutType>
    (popOut, 'pop');
  if (Result = popShowEmbedded) and (ActionType = actShowHTMLEditor) then
    Result := popShowNonModal;
end;

function TPtInfoPresentation.GetSection: TPtInfoSection;
begin
  if (not Assigned(FSection)) then
  begin
    for var I := 0 to OwnerPtInfoData.Sections.Count - 1 do
      if sectionId = OwnerPtInfoData.Sections[I].sectionId then
      begin
        FSection := OwnerPtInfoData.Sections[I];
        if ImageIcon <> '' then
          FSection.FImageWidthCalcNeeded := True;
        break;
      end;
  end;
  Result := FSection;
end;

procedure TPtInfoPresentation.HTMLDialogCloseQuery(Sender: TfrmHTMLDialog;
  Content: TJSONObject; Canceling: Boolean; var CanClose: Boolean);
var
  JSONResults: TJSONValue;
  Results: TPtInfoSaveResults;
  Error: string;
begin
  if Canceling then
  begin
    resetFocus;
    Exit;
  end;
  JSONResults := CreateJSONfromHTMLEditorSave(Content, Error);
  try
    if Error <> '' then
    begin
      ShowMessage(Error);
      CanClose := False;
      exit;
    end
    else if Assigned(JSONResults) then
        begin
          Results := TPtInfoDataConverter.ToObject<TPtInfoSaveResults>
            (JSONResults.ToString);
          try
            if Assigned(OwnerPtInfoData.OwnerPtInfoSplitViewBase) and
              Results.RefreshAllInfoPanels then
              OwnerPtInfoData.OwnerPtInfoSplitViewBase.Reload;
            if Assigned(Results.NoteInformation) and
              (Results.NoteInformation.ID > 0) then
            begin
              Changes.Add(CH_DOC, Results.NoteInformation.ID.ToString,
                Results.NoteInformation.Details, '', CH_SIGN_YES);
              PostMessage(Application.MainForm.Handle, UM_NEWNOTE, 0, 0);
            end;
          finally
            FreeAndNil(Results);
          end;
          resetFocus;
        end
        else
          exit;
  finally
//    FreeAndNil(JSONResults);
  end;
end;

procedure TPtInfoPresentation.HTMLDialogSubmit(Sender: TfrmHTMLDialog;
  Content: TJSONObject);
begin

end;

function TPtInfoPresentation.IsDataValid: Boolean;
var
  MissingData: TPtInfoDataValues;
  I: Integer;
  DoEncounter, DoUser, ReFloat, WasFloating: Boolean;
  dt: TPtInfoDataTypes.TDataType;
  MissingDataTypes: set of TPtInfoDataTypes.TDataType;
  Text: array [TPtInfoDataTypes.TDataType] of string;
  Line, Msg: string;
  FocusedControl: TWinControl;
begin
  Result := True;
  ReFloat := False;
  FocusedControl := Screen.ActiveControl;
  try
    if Assigned(OwnerPtInfoData) and
      Assigned(OwnerPtInfoData.OwnerPtInfoSplitViewBase) then
      WasFloating :=
        (OwnerPtInfoData.OwnerPtInfoSplitViewBase.OpenState = osFloating)
    else
      WasFloating := False;
    if (ActionType in [actShowEditor, actShowHTMLEditor]) or callDetailRPC then
    begin
      DoEncounter := False;
      DoUser := False;
      MissingDataTypes := [];
      MissingData := TPtInfoDataValues.Create;
      try
        RetrieveMissingData(MissingData);
        for I := 0 to MissingData.Count - 1 do
        begin
          if MissingData[I].DataType in [dataEncounterProvider,
            dataVisitInformation] then
            DoEncounter := True;
          if MissingData[I].DataType = dataUserInformation then
            DoUser := True;
        end;
        if DoUser then
          raise Exception.Create('Should ALWAYS have a user');
        if DoEncounter then
        begin
          UpdateEncounter(NPF_ALL);
          frmFrame.DisplayEncounterText;
          ReFloat := True;
        end;
        RetrieveMissingData(MissingData);
        if MissingData.Count > 0 then
        begin
          for I := 0 to MissingData.Count - 1 do
          begin
            include(MissingDataTypes, MissingData[I].DataType);
            Text[MissingData[I].DataType] := MissingData[I]
              .OwnerPtInfoRequiredData.ErrorMessage;
          end;
          Msg := '';
          for dt := Low(TPtInfoDataTypes.TDataType)
            to High(TPtInfoDataTypes.TDataType) do
            if dt in MissingDataTypes then
            begin
              Line := Text[dt];
              if Line = '' then
                Line := copy(GetEnumName(TypeInfo(TPtInfoDataTypes.TDataType),
                  ord(dt)), 5, MaxInt) + ' not defined';
              if not Line.EndsWith('.') then
                Line := Line + '.';
              if Msg <> '' then
                Msg := Msg + CRLF;
              Msg := Msg + Line;
            end;
          if Msg <> '' then
            ShowMessage(Msg);
          Result := False;
        end;
      finally
        FreeAndNil(MissingData);
      end;
    end;
    if Assigned(OwnerPtInfoData) and
      Assigned(OwnerPtInfoData.OwnerPtInfoSplitViewBase) and ReFloat and WasFloating
    then
      OwnerPtInfoData.OwnerPtInfoSplitViewBase.OpenState := osFloating;
  finally
    if ShouldFocus(FocusedControl) then
      FocusedControl.SetFocus;
  end;
end;

procedure TPtInfoPresentation.OrphanPanels;
begin
  if Assigned(FItemPanel) then
    FItemPanel.PtInfoLink.OrphanControl;
end;

procedure TPtInfoPresentation.PanelClick(Sender: TObject);
var
  Panel: TPtInfoPanel;
  InputJSON, JSON: TJSONValue;
  Form: TfrmPtInfoDetails;
  UseForm, Update, SetupNeeded: Boolean;
  FocusedControl: TWinControl;
  Error, formCaption: string;
begin
  if Sender is TPtInfoPanel then
    Panel := Sender as TPtInfoPanel
  else if (Sender is TControl) and (TControl(Sender).Parent is TPtInfoPanel)
  then
    Panel := (TControl(Sender).Parent as TPtInfoPanel)
  else
    Panel := nil;
  if Disabled or (not Assigned(Panel)) or (not IsDataValid) then
    Exit;
  JSON := nil;
  try
    Update := (ActionType = actShowMessage) or (not Assigned(FDialog)) or
      (not(FDialog as TfrmPtInfoDetails).IsActive);
    if callDetailRPC and Update then
    begin
      InputJSON := DataToJSON;
      try
        JSON := CreateJSONFromPanelClick(InputJSON, Error);
        if Error <> '' then
        begin
          ShowMessage(Error);
          Exit;
        end
        else if not Assigned(JSON) then
          Exit;
      finally
        FreeAndNil(InputJSON);
      end;
    end;
    OwnerPtInfoData.OwnerPtInfoSplitViewBase.ResetToCollapse := false;
    if Assigned(OwnerPtInfoData) and
      Assigned(OwnerPtInfoData.OwnerPtInfoSplitViewBase) and
      (OwnerPtInfoData.OwnerPtInfoSplitViewBase.OpenState = osUnpinned) and
      (PopOutType = popShowEmbedded) and (ActionType <> actShowMessage) then
      begin
        OwnerPtInfoData.OwnerPtInfoSplitViewBase.OpenState := osFloating;
        OwnerPtInfoData.OwnerPtInfoSplitViewBase.ResetToCollapse := true;
      end;
    UseForm := (ActionType in [actShowDetail, actShowURL, actShowEditor]);
    if UseForm then
    begin
      Form := GetDetailsForm as TfrmPtInfoDetails;
      SetupNeeded := Update or (not Form.IsActive);
    end
    else
    begin
      Form := nil;
      SetupNeeded := True;
    end;
    Panel.BevelOuter := bvLowered;
    try
      if SetupNeeded then
        case ActionType of
          actNone:
            ;
          actShowDetail:
            PanelShowDetail(Sender, Form, JSON, Update);
          actShowURL:
            PanelShowURL(Sender, Form, JSON, Update);
          actShowMessage:
            PanelShowMessage(Sender, JSON, Update);
          actShowEditor:
            PanelShowEditor(Sender, Form, JSON, Update);
          actShowHTMLEditor:
          begin
            if displayText <> '' then formCaption := displayText
            else if name <> '' then formCaption := name
            else formCaption := 'Information Panel Input Form';
            CreateHTMLForm(JSON, formCaption);
          end;
        end;
      if UseForm then
        if PopOutType = popShowModal then
        begin
          FocusedControl := Screen.ActiveControl;
          try
            Form.ShowModal;
          finally
            if ShouldFocus(FocusedControl) then
              FocusedControl.SetFocus;
          end;
        end
        else
        begin
          if (PopOutType = popShowEmbedded) and (TextWidthByFont(Form.lblHeader.Font.Handle,Form.lblHeader.Caption) > Form.Width) then
            Form.lblHeader.Alignment := taLeftJustify;
          OwnerPtInfoData.OwnerPtInfoSplitViewBase.PanelGrid.Visible :=
            (PopOutType = popShowNonModal);
          OwnerPtInfoData.OwnerPtInfoSplitViewBase.FormGrid.Visible :=
            (PopOutType = popShowEmbedded);
          Form.Show;
          if PopOutType = popShowEmbedded then
          begin
            Form.SetFocus;
            if (ActionType = actShowEditor) and
              (OwnerPtInfoData.OwnerPtInfoSplitViewBase.OpenState = osFloating)
            then
              with OwnerPtInfoData.OwnerPtInfoSplitViewBase do
              begin
                // Fixes display issue where the editor controls may be in the wrong place
                Width := Width + 1;
                Width := Width - 1;
              end;
          end;
        end;
    finally
      Panel.BevelOuter := bvRaised;
    end;
  finally
    FreeAndNil(JSON);
  end;
end;

procedure TPtInfoPresentation.PanelShowDetail(Sender: TObject; AForm: TForm;
  JSON: TJSONValue; Update: Boolean);
var
  Details: string;
  Form: TfrmPtInfoDetails;
begin
  Form := AForm as TfrmPtInfoDetails;
  Form.SetupDetails(dtInfo);
  Details := DetailText;
  if Assigned(JSON) then
    Details := JSON.AsTypeDef<string>('results', Details);
  Form.memDetails.Lines.Text := Details;
  FormatForURLs(Form.memDetails);
  Form.memDetails.ScrollPosition := Point(0, 0);
  Form.memDetails.CaretPos := Point(0, 0);
end;

procedure TPtInfoPresentation.PanelShowEditor(Sender: TObject; AForm: TForm;
  JSON: TJSONValue; Update: Boolean);
var
  Form: TfrmPtInfoDetails;
  GridControls: TControlCollection;
  Panel: TPanel;

begin
  Form := AForm as TfrmPtInfoDetails;
  Form.SetupDetails(dtEditor);
  if Update then
  begin
    if not Assigned(JSON) then
      Exit;
    Form.fraEditGrid.createLayoutFromJSON(DataToJSON, JSON);
    Form.lblHeader.Caption := JSON.AsTypeDef<string>('editor.displayText',
      DisplayText);
    Form.lblHeader.Hint := JSON.AsTypeDef<string>('editor.description', '');
    if Form.lblHeader.Hint <> '' then
      Form.lblHeader.ShowHint := True;
    Form.SetupButtons(JSON.AsTypeDef<string>('editor.buttonTextSave', 'Save'),
      JSON.AsTypeDef<string>('editor.buttonTextCancel', 'Cancel'));
    Form.fraEditGrid.pnlButtons.Visible := not JSON.AsTypeDef<Boolean>
      ('editor.hideButtons', False);
    Form.fraEditGrid.setInitialValues;
    GridControls := Form.fraEditGrid.grdEditPanel.ControlCollection;
    for var I := 0 to GridControls.Count - 1 do
      if GridControls[I].Control is TPanel then
      begin
        Panel := GridControls[I].Control as TPanel;
        for var j := 0 to Panel.ControlCount - 1 do
          if Panel.Controls[j] is TORDateBox then
          begin
            (Panel.Controls[j] as TORDateBox).OnDateDialogOpening :=
              EditorDateBoxOpening;
            (Panel.Controls[j] as TORDateBox).OnDateDialogClosed :=
              EditorDateBoxClosed;
          end
          else if Panel.Controls[j] is TORDateCombo then
          begin
            (Panel.Controls[j] as TORDateCombo).OnDateDialogOpening :=
              EditorDateBoxOpening;
            (Panel.Controls[j] as TORDateCombo).OnDateDialogClosed :=
              EditorDateBoxClosed;
          end;
      end;
  end;
end;

procedure TPtInfoPresentation.PanelShowMessage(Sender: TObject;
  JSON: TJSONValue; Update: Boolean);
var
  Details: string;
begin
  Details := DetailText;
  if Assigned(JSON) then
    Details := JSON.AsTypeDef<string>('results', Details);
  ShowMessage(Details);
  resetFocus;
end;

procedure TPtInfoPresentation.PanelShowURL(Sender: TObject; AForm: TForm;
  JSON: TJSONValue; Update: Boolean);
var
  AURL: string;
  Form: TfrmPtInfoDetails;
begin
  Form := AForm as TfrmPtInfoDetails;
  Form.SetupDetails(dtWeb);
  AURL := URL;
  if Assigned(JSON) then
    AURL := JSON.AsTypeDef<string>('results', AURL);
  AURL := AURL.Replace('%DFN', Patient.DFN);
  AURL := AURL.Replace('%DIVISION', Piece(RPCBrokerV.User.Division, U, 1));
  if RPCBrokerV.ListenerPort > 0 then
    AURL := AURL.Replace('%PORT', RPCBrokerV.ListenerPort.ToString);
  AURL := AURL.Replace('%SRV', RPCBrokerV.Server);
  AURL := AURL.Replace('%STATION', copy(User.StationNumber, 1, 3));
  AURL := AURL.Replace('%DUZ', User.DUZ.ToString);
  Form.wbEdgeBrowser.Navigate(AURL);
end;

procedure TPtInfoPresentation.PopulateOwner(AOwner: TPtInfoData);
begin
  FOwnerPtInfoData := AOwner;
  for var I := 0 to FPtInfoRequiredData.Count - 1 do
    FPtInfoRequiredData[I].PopulateOwner(Self);
end;

procedure TPtInfoPresentation.resetFocus;
begin
  if ItemPanel = nil then exit;
  if ItemPanel.FPtInfoLink = nil then exit;
  if not assigned(ItemPanel.FPtInfoLink.Control) then exit;
  ItemPanel.PtInfoLink.FControl.SetFocus;
  ItemPanel.PtInfoLink.FPresentation.FItemPanel.FPtInfoLink.FControl.SetFocus;
end;

procedure TPtInfoPresentation.ResetFont;
begin
  if Assigned(FDialog) then
    (GetDetailsForm as TfrmPtInfoDetails).ResetFont;
  if Assigned(FItemPanel) then
    FItemPanel.FontSize := MainFontSize;
end;

procedure TPtInfoPresentation.ResetPanelText(UseLongText: Boolean);
begin
  if Assigned(FItemPanel) then
    FItemPanel.ResetPanelText(UseLongText);
end;

procedure TPtInfoPresentation.RetrieveMissingData
  (MissingData: TPtInfoDataValues);
var
  I, j: Integer;
  Value: string;
  DataValue: TPtInfoDataValue;
  Req: TPtInfoDataTypes.TRequiredType;
begin
  MissingData.Clear;
  if Assigned(RequiredData) then
  begin
    for I := 0 to RequiredData.Count - 1 do
    begin
      RequiredData[I].OptionalFound := False;
      RequiredData[I].OptionalCount := 0;
      if RequiredData[I].required and Assigned(RequiredData[I].ReturnData) then
      begin
        for j := 0 to RequiredData[I].ReturnData.Count - 1 do
        begin
          Req := RequiredData[I].ReturnData[j].RequiredType;
          if Req <> reqNo then
          begin
            Value := RetrieveValue(RequiredData[I].DataType,
              RequiredData[I].ReturnData[j].FieldType);
            case Req of
              reqOptional:
                begin
                  inc(RequiredData[I].FOptionalCount);
                  if Value <> '' then
                    RequiredData[I].OptionalFound := True;
                end;
              reqRequired:
                if Value = '' then
                begin
                  DataValue := TPtInfoDataValue.Create(RequiredData[I], Req,
                    RequiredData[I].DataType, RequiredData[I].ReturnData[j]
                    .FieldType);
                  MissingData.Add(DataValue);
                end;
            end;
          end;
        end;
      end;
    end;
    for I := 0 to RequiredData.Count - 1 do
    begin
      if (RequiredData[I].OptionalCount > 0) and
        (not RequiredData[I].OptionalFound) then
      begin
        if RequiredData[I].OptionalCount = 1 then
          Req := reqRequired
        else
          Req := reqOptional;
        if Assigned(RequiredData[I].ReturnData) then
          for j := 0 to RequiredData[I].ReturnData.Count - 1 do
          begin
            if RequiredData[I].ReturnData[j].RequiredType = reqOptional then
            begin
              Value := RetrieveValue(RequiredData[I].DataType,
                RequiredData[I].ReturnData[j].FieldType);
              if Value = '' then
              begin
                DataValue := TPtInfoDataValue.Create(RequiredData[I], Req,
                  RequiredData[I].DataType, RequiredData[I].ReturnData[j]
                  .FieldType);
                MissingData.Add(DataValue);
              end;
            end;
          end;
      end;
    end;
  end;
end;

function TPtInfoPresentation.RetrieveValue
  (ADataType: TPtInfoDataTypes.TDataType;
  AFieldType: TPtInfoDataTypes.TFieldType): string;
begin
  Result := '';
  case ADataType of
    dataDivision:
      case AFieldType of
        fldID:
          Result := Piece(RPCBrokerV.User.Division, U, 1);
        fldName:
          Result := Piece(RPCBrokerV.User.Division, U, 2);
      end;
    dataPort:
      case AFieldType of
        fldID:
          if RPCBrokerV.ListenerPort > 0 then
            Result := RPCBrokerV.ListenerPort.ToString;
      end;
    dataServer:
      case AFieldType of
        fldID:
          Result := RPCBrokerV.Server;
      end;
    dataStationNumber:
      case AFieldType of
        fldID:
          Result := copy(User.StationNumber, 1, 3);
      end;
    dataEncounterProvider:
      case AFieldType of
        fldID:
          if Encounter.Provider > 0 then
            Result := Encounter.Provider.ToString;
        fldName:
          Result := Encounter.ProviderName;
      end;
    dataUserInformation:
      case AFieldType of
        fldID:
          if User.DUZ > 0 then
            Result := User.DUZ.ToString;
        fldName:
          Result := User.Name;
      end;
    dataVisitInformation:
      case AFieldType of
        fldLocID:
          if Encounter.Location > 0 then
            Result := Encounter.Location.ToString;
        fldLocName:
          Result := Encounter.LocationName;
        fldVisitDateTime:
          if Encounter.DateTime > 0 then
            Result := Encounter.DateTime.ToString;
        fldVisitType:
          Result := Encounter.VisitCategory;
        fldVisitString:
          begin
            Result := Encounter.VisitStr;
            if Result = EMPTY_VISIT_STRING then
              Result := '';
          end;
      end;
  end;
end;

procedure TPtInfoPresentation.SetColor(const Value: string);
begin
  inherited Color := Value;
end;

procedure TPtInfoPresentation.SetImageIcon(const Value: string);
begin
  inherited ImageIcon := Value;
end;

procedure TPtInfoPresentation.SetupPanels(ARowHeight: Integer);
var
  Panel: TPtInfoPanel;
  Row: TRowItem;
begin
  if Assigned(Section) and ((not Section.Collapsible) or (not Section.Collapsed))
  then
  begin
    if Assigned(FItemPanel) then
      Panel := FItemPanel
    else
    begin
      Panel := TPtInfoPanel.Create(nil, Self,
        OwnerPtInfoData.OwnerPtInfoSplitViewBase.PanelGrid);
      FItemPanel := Panel;
      Panel.ParentColor := False;
      if Color = '' then
        Panel.Color := OwnerPtInfoData.GeneralParameters.DefaultColorValue
      else
        Panel.Color := ColorValue;
      Panel.TabStop := True;
      if ActionType <> actNone then
        Panel.OnClick := PanelClick;
      Panel.FLongText := DisplayText;
      Panel.FShortText := AbbreviatedDisplayText;
    end;
    if Disabled then
      Panel.Font.Color := clGrayText;
    Panel.FontSize := MainFontSize;
    Panel.PtInfoLink.GridPanel.RowCollection.BeginUpdate;
    try
      Row := Panel.PtInfoLink.GridPanel.RowCollection.Add;
      Row.SizeStyle := ssAbsolute;
      Row.Value := ARowHeight;
    finally
      Panel.PtInfoLink.GridPanel.RowCollection.EndUpdate;
    end;
    Panel.PtInfoLink.GridPanel.ControlCollection.AddControl(Panel, 0,
      Row.Index);
    Panel.Parent := Panel.PtInfoLink.GridPanel;
    Panel.Align := alClient;
    Panel.Visible := True;
  end;
end;

function TPtInfoPresentation.ShouldDisplayPanel(PageID: Integer): Boolean;
begin
  Result := Assigned(Section) and ((Section.PageID = CT_NOPAGE) or
    (Section.PageID = PageID));
end;

{ TPtInfoSection }

function TPtInfoSection.CalcImageWidth(ImageData: string): Integer;
begin
  if (ImageData = '') or (not OwnerPtInfoData.GeneralParameters.ImageIconEnabled)
  then
    Result := 0
  else if OwnerPtInfoData.IsImageIconSymbol(ImageData) then
  begin
    OwnerPtInfoData.OwnerPtInfoSplitViewBase.SymbolLabel.Font.Size :=
      MainFontSize + TPtInfoDataTypes.SymbolFontOffset;
    OwnerPtInfoData.OwnerPtInfoSplitViewBase.SymbolLabel.Symbol.FromString
      (ImageData);
    Result := OwnerPtInfoData.OwnerPtInfoSplitViewBase.SymbolLabel.SymbolSize;
  end
  else
    Result := OwnerPtInfoData.RowHeight - TPtInfoDataTypes.ImageMarginSizeTop
      [MainFont.Size] - TPtInfoDataTypes.ImageMarginSizeBottom
      [MainFont.Size] - 2;
end;

function TPtInfoSection.GetColor: string;
begin
  if OwnerPtInfoData.GeneralParameters.colorEnabled then
    Result := inherited Color
  else
    Result := '';
end;

function TPtInfoSection.GetColorValue: TColor;
begin
  if OwnerPtInfoData.GeneralParameters.colorEnabled then
  begin
    if Color <> '' then
      Result := StringToColor(Color)
    else
      Result := OwnerPtInfoData.GeneralParameters.DefaultColorValue;
  end
  else
    Result := TPtInfoDataTypes.MainDefaultColorValue;
end;

function TPtInfoSection.GetHasImages: Boolean;
var
  I: Integer;
begin
  if (not OwnerPtInfoData.GeneralParameters.ImageIconEnabled) then
    Result := False
  else if ImageIcon <> '' then
    Result := True
  else
  begin
    if Assigned(OwnerPtInfoData.Presentation) then
      for I := 0 to OwnerPtInfoData.Presentation.Count - 1 do
        if (OwnerPtInfoData.Presentation[I].Section.sectionId = sectionId) and
          (OwnerPtInfoData.Presentation[I].ImageIcon <> '') then
          Exit(True);
    Result := False;
  end;
end;

function TPtInfoSection.GetImageIcon: string;
begin
  if OwnerPtInfoData.GeneralParameters.ImageIconEnabled then
    Result := inherited ImageIcon
  else
    Result := '';
end;

function TPtInfoSection.GetImageWidth: Integer;
var
  I, len: Integer;

begin
  if FImageWidthCalcNeeded then
  begin
    FImageWidth := 0;
    if HasImages then
    begin
      if not Collapsible then
        FImageWidth := CalcImageWidth(ImageIcon);
      if (not Collapsible) or (not Collapsed) then
        for I := 0 to OwnerPtInfoData.Presentation.Count - 1 do
        begin
          if (OwnerPtInfoData.Presentation[I].Section.sectionId = sectionId)
          then
          begin
            len := CalcImageWidth(OwnerPtInfoData.Presentation[I].ImageIcon);
            if FImageWidth < len then
              FImageWidth := len;
          end;
        end;
    end;
    FImageWidthCalcNeeded := False;
  end;
  Result := FImageWidth;
end;

procedure TPtInfoSection.OrphanPanels;
begin
  if Assigned(FSectionPanel) then
    FSectionPanel.PtInfoLink.OrphanControl;
end;

procedure TPtInfoSection.PanelClick(Sender: TObject);
begin
  FCollapsed := not FCollapsed;
  OwnerPtInfoData.FResetPanels := True;
  FClicked := true;
  PostMessage(OwnerPtInfoData.OwnerPtInfoSplitViewBase.Handle, UM_MISC, 0, 0);
end;

procedure TPtInfoSection.PopulateOwner(AOwner: TPtInfoData);
begin
  FOwnerPtInfoData := AOwner;
end;

procedure TPtInfoSection.ResetFont;
begin
  if Assigned(FSectionPanel) then
    (FSectionPanel as TPtInfoPanel).FontSize := MainFontSize;
end;

procedure TPtInfoSection.ResetPanelText(UseLongText: Boolean);
begin
  if Assigned(FSectionPanel) then
    (FSectionPanel as TPtInfoPanel).ResetPanelText(UseLongText);
end;

procedure TPtInfoSection.SetColor(const Value: string);
begin
  inherited Color := Value;
end;

procedure TPtInfoSection.SetImageIcon(const Value: string);
begin
  inherited ImageIcon := Value;
end;

procedure TPtInfoSection.SetupSection(ARowHeight: Integer);
var
  Panel: TPtInfoPanel;
  Row: TRowItem;
  PanelFocus: boolean;
begin
  PanelFocus := false;
  if (AbbreviatedDisplayText = '') and (DisplayText = '') and (not Collapsible)
    and ((ImageIcon = '') or
    (not OwnerPtInfoData.GeneralParameters.ImageIconEnabled)) then
    Exit;
  if Assigned(FSectionPanel) then
    Panel := FSectionPanel.PtInfoLink.Control as TPtInfoPanel
  else
  begin
    Panel := TPtInfoPanel.Create(Self, nil,
      OwnerPtInfoData.OwnerPtInfoSplitViewBase.PanelGrid);
    FSectionPanel := Panel;
    if OwnerPtInfoData.GeneralParameters.colorEnabled then
    begin
      if Color = '' then
        Panel.Color := OwnerPtInfoData.GeneralParameters.DefaultColorValue
      else
        Panel.Color := ColorValue;
    end
    else
      Panel.Color := TPtInfoDataTypes.MainDefaultColorValue;
    Panel.FLongText := DisplayText;
    Panel.FShortText := AbbreviatedDisplayText;
    Panel.BevelOuter := bvNone;
    Panel.TextLabel.Font.Style := [fsBold];
  end;
  if Collapsible then
  begin
    Panel.OnClick := PanelClick;
    Panel.TabStop := True;
    if FClicked then PanelFocus := true;
    FClicked := false;
    if Assigned(Panel.ExpandImage) then
    begin
      if Collapsed then
        Panel.ExpandImage.Picture.Assign
          (OwnerPtInfoData.OwnerPtInfoSplitViewBase.ImageExpand.Picture)
      else
        Panel.ExpandImage.Picture.Assign
          (OwnerPtInfoData.OwnerPtInfoSplitViewBase.ImageCollapse.Picture);
    end;
  end
  else
    begin
      Panel.OnClick := nil;
      if screenReaderActive then Panel.TabStop := true;
    end;
  if Disabled then
    Panel.TextLabel.Enabled := False;
  Panel.FontSize := MainFontSize;
  Panel.PtInfoLink.GridPanel.RowCollection.BeginUpdate;
  try
    Row := Panel.PtInfoLink.GridPanel.RowCollection.Add;
    Row.SizeStyle := ssAbsolute;
    Row.Value := ARowHeight;
  finally
    Panel.PtInfoLink.GridPanel.RowCollection.EndUpdate;
  end;
  Panel.PtInfoLink.GridPanel.ControlCollection.AddControl(Panel, 0, Row.Index);
  Panel.Parent := Panel.PtInfoLink.GridPanel;
  Panel.Align := alClient;
  Panel.Visible := True;
  if PanelFocus then FSectionPanel.FPtInfoLink.FControl.SetFocus;

end;

{ TSaveResults }

constructor TPtInfoSaveResults.Create;
begin
  inherited Create;
  FPtInfoNoteInfo := TPtInfoNoteInfo.Create;
end;

destructor TPtInfoSaveResults.Destroy;
begin
  FreeAndNil(FPtInfoNoteInfo);
  inherited;
end;

{ TPtInfoData }

procedure TPtInfoData.AdjustPanels;
const
  MinGap = 8;
var
  I, GapCount, Min, Adjust, PanelCount, BevelWidth: Integer;
  Grid: TGridPanel;
  Rows: TRowCollection;
  Gap: Double;
  ScrollBarsNeeded, ResetNeeded: Boolean;
  IsGapRow: TArray<Boolean>;
  Control: TControl;
  Row: TCellItem;
  PanelAlign: TAlign;
begin
  if not Assigned(OwnerPtInfoSplitViewBase) then
    Exit;
  Min := 0;
  GapCount := 0;
  PanelCount := 0;
  Grid := OwnerPtInfoSplitViewBase.PanelGrid;
  Rows := Grid.RowCollection;
  SetLength(IsGapRow, Rows.Count);
  for I := 0 to Rows.Count - 1 do
  begin
    Control := Grid.ControlCollection.Controls[0, I];
    IsGapRow[I] := not(Assigned(Control) and (Control is TPtInfoPanel));
    if IsGapRow[I] then
    begin
      inc(GapCount);
      inc(Min, MinGap);
    end
    else
    begin
      inc(PanelCount);
      inc(Min, FRowHeight);
    end
  end;
  if HasImages then
    Adjust := 6
  else
    Adjust := 8;
  while (Adjust > 0) and ((Min + (Adjust * PanelCount)) > Grid.Parent.Height) do
    dec(Adjust, 2);
  ScrollBarsNeeded := (Min + (Adjust * PanelCount)) > Grid.Parent.Height;
  if GapCount < 1 then
    GapCount := 1;
  Gap := 100 / GapCount;
  ResetNeeded := False;
  Rows.BeginUpdate;
  try
    if ScrollBarsNeeded then
      PanelAlign := alTop
    else
      PanelAlign := alClient;
    if Grid.Align <> PanelAlign then
    begin
      Grid.Align := PanelAlign;
      ResetNeeded := True;
    end;
    if ScrollBarsNeeded then
      Grid.Height := Min;
    if Adjust > 0 then
      BevelWidth := 2
    else
      BevelWidth := 1;
    for I := 0 to Rows.Count - 1 do
    begin
      Row := Rows[I];
      if IsGapRow[I] then
      begin
        if ScrollBarsNeeded then
        begin
          Row.SizeStyle := ssAbsolute;
          Row.Value := MinGap;
        end
        else
        begin
          Row.SizeStyle := ssPercent;
          Row.Value := Gap;
        end;
      end
      else
      begin
        Row.SizeStyle := ssAbsolute;
        Row.Value := FRowHeight + Adjust;
        Control := Grid.ControlCollection.Controls[0, I];
        if Assigned(Control) and (Control is TPtInfoPanel) then
        begin
          if TPtInfoPanel(Control).BevelWidth <> BevelWidth then
          begin
            TPtInfoPanel(Control).BevelWidth := BevelWidth;
            ResetNeeded := True;
          end
        end;
      end
    end;
  finally
    Rows.EndUpdate;
  end;
  if ResetNeeded then
    OwnerPtInfoSplitViewBase.ResetOpenState;
end;

procedure TPtInfoData.CloseAllDetails;
begin
  for var I := 0 to Presentation.Count - 1 do
    Presentation[I].CloseDetailsForm;
end;

procedure TPtInfoData.CloseEmbeddedDetails(AForm: TForm);
begin
  for var I := 0 to Presentation.Count - 1 do
    Presentation[I].CloseEmbeddedForm(AForm);
end;

constructor TPtInfoData.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TGeneralParameters), Self, 'FGeneralParameters');
  FPtInfoGeneralParameters := TPtInfoGeneralParameters.Create;
  FreeAndNilOld(TypeInfo(TObjectList<TPresentation>), Self, 'FPresentation');
  FPtInfoPresentation := TObjectList<TPtInfoPresentation>.Create(True);
  FreeAndNilOld(TypeInfo(TObjectList<TSection>), Self, 'FSections');
  FPtInfoSections := TObjectList<TPtInfoSection>.Create(True);
end;

destructor TPtInfoData.Destroy;
begin
  if Assigned(FHTMLDialogIDs) then
  begin
    for var I := 0 to FHTMLDialogIDs.Count - 1 do
      TfrmHTMLDialog.DestroyDialog(FHTMLDialogIDs[I]);
    FreeAndNil(FHTMLDialogIDs);
  end;
  FreeAndNil(FPtInfoSections);
  FreeAndNil(FPtInfoPresentation);
  FreeAndNil(FPtInfoGeneralParameters);
  inherited;
end;

function TPtInfoData.GetCurrentEmbeddedPresentation: TPtInfoPresentation;
var
  I: Integer;
begin
  for I := 0 to FPtInfoPresentation.Count - 1 do
    if Assigned(FPtInfoPresentation[I].FDialog) and
      (FPtInfoPresentation[I].FDialog.Parent = OwnerPtInfoSplitViewBase.FormGrid)
    then
      Exit(FPtInfoPresentation[I]);
  Result := nil;
end;

function TPtInfoData.GetHasImages: Boolean;
begin
  Result := False;
  if not GeneralParameters.ImageIconEnabled then
    Exit;
  for var I := 0 to Sections.Count - 1 do
    if Sections[I].HasImages then
      Exit(True);
end;

procedure TPtInfoData.HTMLDialogCreate(ID: string);
begin
  if not Assigned(FHTMLDialogIDs) then
    FHTMLDialogIDs := TStringList.Create;
  if FHTMLDialogIDs.IndexOf(ID) < 0 then
    FHTMLDialogIDs.Add(ID);
end;

class function TPtInfoData.IsImageIconSymbol(ImageData: string): Boolean;
begin
  Result := (pos(';', ImageData) > 0) or (Length(ImageData) < 6);
end;

procedure TPtInfoData.PopulateOwner(AOwner: TPtInfoSplitViewBase);
begin
  FOwnerPtInfoSplitViewBase := AOwner;
  FPtInfoGeneralParameters.PopulateOwner(Self);
  for var I := 0 to FPtInfoPresentation.Count - 1 do
    FPtInfoPresentation[I].PopulateOwner(Self);
  for var I := 0 to FPtInfoSections.Count - 1 do
    FPtInfoSections[I].PopulateOwner(Self);
end;

procedure TPtInfoData.ResetFont(ARowHeight: Integer);
var
  I: Integer;
begin
  FRowHeight := ARowHeight;
  for I := 0 to Sections.Count - 1 do
  begin
    Sections[I].FImageWidthCalcNeeded := True;
    Sections[I].ResetFont;
  end;
  for I := 0 to Presentation.Count - 1 do
    Presentation[I].ResetFont;
end;

procedure TPtInfoData.ResetPanelText(UseLongText: Boolean);
var
  I: Integer;
begin
  for I := 0 to Sections.Count - 1 do
    Sections[I].ResetPanelText(UseLongText);
  for I := 0 to Presentation.Count - 1 do
    Presentation[I].ResetPanelText(UseLongText);
end;

function TPtInfoData.SetupPanels(PageID, ARowHeight: Integer): Boolean;
var
  I, j, GapCount: Integer;
  HasNational, HasLocal, NeedGap: Boolean;
  Gap: Double;

  procedure AddGap;
  var
    Row: TRowItem;
  begin
    if NeedGap then
    begin
      Row := Self.OwnerPtInfoSplitViewBase.PanelGrid.RowCollection.Add;
      Row.SizeStyle := ssPercent;
      Row.Value := Gap;
    end;
  end;

begin
  Result := False;
  FRowHeight := ARowHeight;
  OwnerPtInfoSplitViewBase.PanelGrid.BeginUpdate;
  try
    for I := 0 to Presentation.Count - 1 do
      Presentation[I].OrphanPanels;
    for I := 0 to Sections.Count - 1 do
    begin
      Sections[I].OrphanPanels;
      Sections[I].Used := False;
    end;
    OwnerPtInfoSplitViewBase.PanelGrid.ControlCollection.Clear;
    OwnerPtInfoSplitViewBase.PanelGrid.RowCollection.Clear;
    for I := 0 to Presentation.Count - 1 do
      if Presentation[I].ShouldDisplayPanel(PageID) and
        Assigned(Presentation[I].Section) then
        Presentation[I].Section.Used := True;
    GapCount := 0;
    HasNational := False;
    HasLocal := False;
    for I := 0 to Sections.Count - 1 do
      if Sections[I].Used then
      begin
        if Sections[I].IsNational then
          HasNational := True
        else
          HasLocal := True;
        inc(GapCount);
      end;
    if HasNational and HasLocal then
      dec(GapCount);
    if GapCount <= 0 then
      Exit;
    Gap := 100.0 / GapCount;
    NeedGap := not HasNational;
    for var National := True downto False do
    begin
      for I := 0 to Sections.Count - 1 do
        if Sections[I].Used and (Sections[I].IsNational = National) then
        begin
          AddGap;
          NeedGap := True;
          Sections[I].SetupSection(ARowHeight);
          for j := 0 to Presentation.Count - 1 do
            if Presentation[j].ShouldDisplayPanel(PageID) and
              (Presentation[j].Section = Sections[I]) then
            begin
              Presentation[j].SetupPanels(ARowHeight);
              Result := True;
            end;
        end;
    end;
    if HasLocal then
      NeedGap := False;
    AddGap;
  finally
    OwnerPtInfoSplitViewBase.PanelGrid.EndUpdate;
  end;
  ResetFont(ARowHeight);
  AdjustPanels;
  ResetPanelText(OwnerPtInfoSplitViewBase.OpenState <> osUnpinned);
end;

{ TPtInfoDataConverter }

class function TPtInfoDataConverter.InternalToObject<T, U>(JSONValue: TJSONValue; JSONString: string; AOwner: U): T;
var
  Ctx: TRttiContext;
  LArgs: array of TValue;
  LMethod: TRttiMethod;
  LType: TRttiType;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  if Assigned(JSONValue) then
    Result := TJSONMapper<T>.Default.FromObject(JSONValue)
  else
    Result := TJSONMapper<T>.Default.FromObject(JSONString);
  Ctx := TRttiContext.Create;
  try
    LType := Ctx.GetType(Result.ClassInfo);
    for LMethod in LType.GetMethods do
    if Assigned(LMethod) and LMethod.HasName('PopulateOwner') then
    begin
      if Length(LMethod.GetParameters) > 0 then
      begin
        SetLength(LArgs, 1);
        LArgs[0] := TValue.From<U>(AOwner);
      end;
      LMethod.Invoke(Result, LArgs);
      exit;
    end;
  finally
    Ctx.Free;
  end;
end;

class function TPtInfoDataConverter.LibraryName: string;
begin
  Result := QualifiedClassName;
  if Result.EndsWith('.' + ClassName) then
    delete(Result, Length(QualifiedClassName) - Length(ClassName) - 1, MaxInt);
end;

class function TPtInfoDataConverter.ToJSON<T>(AObject: T): string;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  Result := TJSONMapper<T>.Default.ToString(AObject);
end;

class function TPtInfoDataConverter.ToObject<T, U>(JSON: TJSONValue; AOwner: U): T;
begin
  Result := InternalToObject<T, U>(JSON, '', AOwner);
end;

class function TPtInfoDataConverter.ToObject<T, U>(JSON: string; AOwner: U): T;
begin
  Result := InternalToObject<T, U>(nil, JSON, AOwner);
end;

class function TPtInfoDataConverter.ToObject<T>(JSON: string): T;
begin
  Result := InternalToObject<T, TObject>(nil, JSON, nil);
end;

class function TPtInfoDataConverter.ToObject<T>(JSON: TJSONValue): T;
begin
  Result := InternalToObject<T, TObject>(JSON, '', nil);
end;

type
  TJsonListConverterPtInfoReturnData = class
    (TJsonTypedListConverter<TPtInfoReturnData>);
  TJsonListConverterPtInfoRequiredData = class
    (TJsonTypedListConverter<TPtInfoRequiredData>);
  TJsonListConverterPtInfoPresentation = class
    (TJsonTypedListConverter<TPtInfoPresentation>);
  TJsonListConverterPtInfoSection = class
    (TJsonTypedListConverter<TPtInfoSection>);

  TPtInfoDataJSONSerializer = class(TJsonSerializer)
  public
    constructor Create;
  end;

  { TPtInfoDataJSONSerializer }

constructor TPtInfoDataJSONSerializer.Create;
var
  AAttributes: TJsonDynamicAttributes;
  AFieldType: TRttiType;
  AResolver: TJsonDynamicContractResolver;
  Ctx: TRttiContext;

  procedure Init;
  var
    LField: TRttiField;
  begin
    AResolver := TJsonDynamicContractResolver.Create
      (TJsonMemberSerialization.Public);
    ContractResolver := AResolver;
    LField := TRttiUtils.GetRttiField(TypeInfo(TJsonDynamicContractResolver),
      'FDynamicAttributes');
    if Assigned(LField) then
      AAttributes := LField.GetValue(AResolver).AsType<TJsonDynamicAttributes>
    else
      AAttributes := nil;
    AFieldType := Ctx.GetType(TRttiType);
  end;

  procedure IgnoreProperties(AClass: TClass; ATypeInf: PTypeInfo);
  var
    I, j: Integer;
    LProp: TRttiProperty;
    LType: TRttiType;
    PropList: TArray<string>;
  begin
    LType := Ctx.GetType(ATypeInf);
    for LProp in LType.GetProperties do
    begin
      if LProp.HasAttribute<JsonInAttribute> then
        continue;
      if (not(LProp.Visibility in [mvPublic, mvPublished])) or
        (LProp.Parent.Name <> AClass.ClassName) then
      begin
        SetLength(PropList, Length(PropList) + 1);
        PropList[Length(PropList) - 1] := LProp.Name;
      end;
    end;
    for I := Length(PropList) - 1 downto 0 do
      for LProp in LType.GetProperties do
        if (CompareText(PropList[I], LProp.Name) = 0) and
          (LProp.Parent.Name = AClass.ClassName) then
        begin
          AResolver.SetPropertyName(ATypeInf, PropList[I], LProp.Name);
          for j := I to Length(PropList) - 2 do
            PropList[j] := PropList[j + 1];
          SetLength(PropList, Length(PropList) - 1);
          AAttributes.AddAttribute(LProp, JsonIgnoreAttribute.Create);
          break;
        end;
    AResolver.SetPropertiesIgnored(ATypeInf, PropList);
  end;

begin
  inherited Create;
  Ctx := TRttiContext.Create;
  try
    Init;
    IgnoreProperties(TReturnData, TypeInfo(TPtInfoReturnData));
    IgnoreProperties(TRequiredData, TypeInfo(TPtInfoRequiredData));
    IgnoreProperties(TGeneralParameters, TypeInfo(TPtInfoGeneralParameters));
    IgnoreProperties(TPresentation, TypeInfo(TPtInfoPresentation));
    IgnoreProperties(TSection, TypeInfo(TPtInfoSection));
    IgnoreProperties(TData, TypeInfo(TPtInfoData));
    AResolver.SetPropertyConverter(TypeInfo(TPtInfoRequiredData), 'ReturnData',
      TJsonListConverterPtInfoReturnData);
    AResolver.SetPropertyConverter(TypeInfo(TPtInfoPresentation),
      'RequiredData', TJsonListConverterPtInfoRequiredData);
    AResolver.SetPropertyConverter(TypeInfo(TPtInfoData), 'Presentation',
      TJsonListConverterPtInfoPresentation);
    AResolver.SetPropertyConverter(TypeInfo(TPtInfoData), 'Sections',
      TJsonListConverterPtInfoSection);
  finally
    Ctx.Free;
  end;
end;

initialization

PtInfoDataJSONLibrary := TPtInfoDataConverter.LibraryName;
PtInfoDataJSONSerializerRegistered := TJSONMappers.RegisterLibrary
  (PtInfoDataJSONLibrary, TJSONMappers.TOptionality.DontCare,
  TJSONMappers.TOptionality.DontCare, TJSONMappers.TOptionality.DontCare,
  procedure(const AName: string; const ASerItems: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  const
    CSerItems: array [TJSONMappers.TItem] of string = ('Public', 'Fields');
  begin
    AIntro := '[JsonSerialize(TJsonMemberSerialization.' + CSerItems
      [ASerItems] + ')]';
    AReqUnit := PtInfoDataJSONLibrary;
  end,
  procedure(const AName, AOrigName: string; const AElem: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  begin
    if AnsiSameText(AName, AOrigName) and (AElem <> TJSONMappers.TItem.Field)
    then
      Exit;
    AIntro := '[JsonName(''' + AOrigName + ''')]';
    AReqUnit := PtInfoDataJSONLibrary;
  end,
  procedure(const AItemType: string; var AIntro, AReqUnit,
    AInstantiation: string)
  begin
    var
    LConv := StringReplace(AItemType, '<', '', [TReplaceFlag.rfReplaceAll]);
    LConv := 'TJsonListConverter' + StringReplace(LConv, '>', '',
      [TReplaceFlag.rfReplaceAll]);
    AIntro := '[JsonConverter(' + LConv + ')]';
    AReqUnit := PtInfoDataJSONLibrary;
    AInstantiation := LConv + ' = class(TJsonListConverter<' + AItemType + '>)';
  end,
  function(ApValue: Pointer; ApTypeInfo: PTypeInfo): TJSONObject
  var
    LSer: TPtInfoDataJSONSerializer;
    LWrt: TJsonObjectWriter;
    V: TValue;
  begin
    LSer := TPtInfoDataJSONSerializer.Create;
    LWrt := TJsonObjectWriter.Create(False);
    try
      TValue.Make(ApValue, ApTypeInfo, V);
      LSer.Serialize(LWrt, V);
      Result := LWrt.JSON as TJSONObject;
    finally
      LWrt.Free;
      LSer.Free;
    end;
  end,
  function(AValue: TJSONObject; ApTypeInfo: PTypeInfo): TValue
  var
    LSer: TPtInfoDataJSONSerializer;
    LRdr: TJsonObjectReader;
  begin
    LSer := TPtInfoDataJSONSerializer.Create;
    LRdr := TJsonObjectReader.Create(AValue);
    try
      Result := LSer.Deserialize(LRdr, ApTypeInfo);
    finally
      LRdr.Free;
      LSer.Free;
    end;
  end);

finalization

if PtInfoDataJSONSerializerRegistered then
  TJSONMappers.UnRegisterLibrary(PtInfoDataJSONLibrary);

end.

