unit uGMV_RPC_Names;

interface
const
//  RPC_ICN_TO_DFN = 'VAFCTFU CONVERT ICN TO DFN';
//  RPC_DFN_TO_ICN = 'VAFCTFU CONVERT DFN TO ICN';
  RPC_PATIENT_ALLERGIES = 'GMV ALLERGY';
  RPC_CLINIC_PATIENTS = 'GMV CLINIC PT';
  RPC_DATE_CONVERT = 'GMV CONVERT DATE';
  RPC_CurrentTime = 'GMV GET CURRENT TIME'; // 1
  RPC_PARAMETER = 'GMV PARAMETER';
  RPC_MANAGER = 'GMV MANAGER';
  RPC_CREATECONTEXT = 'GMV V/M GUI';
  RPC_PATIENT_VITALS_ALL = 'GMV V/M ALLDATA';
  RPC_VITALS_QUALIFIERS = 'GMV VITALS/CAT/QUAL'; // 2
  RPC_PATIENT_LATEST_VITALS = 'GMV LATEST VM'; // ?

  RPC_PATIENT_SELECT = 'GMV PTSELECT';

  RPC_VITAL_TYPE_IEN = 'GMV GET VITAL TYPE IEN'; // 3
  RPC_VITAL_CATEGORY_IEN = 'GMV GET CATEGORY IEN';
  RPC_VITAL_ADD_VALUE = 'GMV ADD VM';
  RPC_NUR_UNIT_PATIENTS = 'GMV NUR UNIT PT';
  RPC_TEAM_PATIENTS = 'GMV TEAM PATIENTS';
  RPC_WARD_LOCATION = 'GMV WARD LOCATION';
  RPC_ROOM_BED = 'GMV ROOM/BED';

  RPC_GMV_RECORD = 'GMV EXTRACT REC'; // entered in error
  RPC_GMV_MARK_ERROR = 'GMV MARK ERROR';

  RPC_USER = 'GMV USER'; // 4
  RPC_WARD_PATIENTS = 'GMV WARD PT';

  RPC_QUALIFIER_TABLE = 'GMV QUALIFIER TABLE';

  RPC_PATIENTINFO = 'ORWPT PTINQ';

  RPC_DLL_VERSION = 'GMV DLL VERSION';

  RPC_CHECK_DEVICE = 'GMV CHECK DEVICE';

  RPC_LOCATION_SELECT = 'GMV LOCATION SELECT';

  RPC_CLOSEST_READING = 'GMV CLOSEST READING';

implementation

end.
