'''
Created on Jun 14, 2012

@author: bcaine
'''
from Actions import Actions
import TestHelper
import datetime
import time

class SCActions (Actions):
    def __init__(self, VistAconn, scheduling=None, user=None, code=None):
        Actions.__init__(self, VistAconn, scheduling, user, code)

    def signon (self):
        if self.acode is None:
            self.VistA.wait('')
            self.VistA.write('S DUZ=1 D ^XUP')
            if self.sched is not None:
                self.VistA.wait('OPTION NAME:')
                self.VistA.write('SDAM APPT MGT')
        else:
            self.VistA.wait('');
            self.VistA.write('D ^ZU')
            self.VistA.wait('ACCESS CODE:');
            self.VistA.write(self.acode)
            self.VistA.wait('VERIFY CODE:');
            self.VistA.write(self.vcode)
            self.VistA.wait('//');
            self.VistA.write('')
            self.VistA.wait('Option:')
            self.VistA.write('Scheduling')

    def schtime(self, plushour=1):
        '''Calculates a time for the next hour'''
        now = datetime.datetime.now()
        hour = now.hour + plushour
        if hour == 12:
            am_pm = 'PM'
        elif hour == 24:
            hour=0
            am_pm = 'AM'
        elif hour > 12 and (hour is not 24):
            am_pm = 'PM'
            hour = hour - 12
        else:
            am_pm = 'AM'
        time = 't@' + str(hour) + am_pm
        return time

    def getclinic(self):
        '''Determines which clinic to use based on the time of day'''
        now = datetime.datetime.now()
        hour = now.hour
        if (hour>=23 and hour<=24) or (hour>=0 and hour<=6):
            clinic='Clinic1'
        elif hour>=7 and hour<=14:
            clinic='Clinic2'
        elif hour>=15 and hour<=22:
            clinic='Clinic3'
        return clinic

    def dateformat(self, dayadd=0):
        '''Currently not used, needs to be able to handle when the added days
        puts the total days over the months total (ei change 8/35/12 to 9/3/12).
        Idea is to use for date verification'''
        now = datetime.datetime.now()
        month = now.month
        day = now.day + dayadd
        year = now.year % 20
        date = str(month) + '/' + str(day) + '/' + str(year)
        return date

    def makeapp(self, patient, datetime, fresh=None):
        '''Makes Appointment for specified user at specified time'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('MA')
        self.VistA.wait('PATIENT NAME:')
        self.VistA.write(patient)
        self.VistA.wait('TYPE:')
        self.VistA.write('Regular')
        if fresh is not None:
            self.VistA.wait('APPOINTMENTS:')
            self.VistA.write('Yes')
        self.VistA.wait('ETHNICITY:')
        self.VistA.write('')
        self.VistA.wait('RACE:')
        self.VistA.write('')
        self.VistA.wait('COUNTRY:')
        self.VistA.write('')
        self.VistA.wait('STREET ADDRESS')
        self.VistA.write('')
        self.VistA.wait('ZIP')
        self.VistA.write('')
        for x in range(0, 2):
            self.VistA.wait('PHONE NUMBER')
            self.VistA.write('')
        self.VistA.wait('BAD ADDRESS')
        self.VistA.write('')
        self.VistA.wait('above changes?')
        self.VistA.write('No')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('REQUEST?')
        self.VistA.write('Yes')
        self.VistA.wait('DATE/TIME')
        self.VistA.write(datetime)
        self.VistA.wait('CORRECT?')
        self.VistA.write('Yes')
        self.VistA.wait('STOPS?')
        self.VistA.write('No')
        self.VistA.wait('OTHER INFO:')
        self.VistA.write('')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('Quit')
        self.VistA.wait('')

    def canapp(self, mult=None):
        '''Cancel an Appointment, if there are multiple apts on schedule, send a string to the parameter "first"'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('CA')
        if mult is not None:
            #If there are more than 1 appointments
            self.VistA.wait('Select Appointment')
            self.VistA.write(mult)
        self.VistA.wait('linic:')
        self.VistA.write('Clinic')
        self.VistA.wait('REASONS NAME')
        self.VistA.write('Clinic Cancelled')
        self.VistA.wait('REMARKS:')
        self.VistA.write('')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('CANCELLED?')
        self.VistA.write('')
        self.VistA.wait('CANCELLED')
        self.VistA.write('')
        self.VistA.wait('exit:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def noshow(self, appnum):
        '''Registers a patient as a no show'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('NS')
        self.VistA.wait('Select Appointment')
        self.VistA.write(appnum)
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('NOW?')
        self.VistA.write('')
        self.VistA.wait('NOW?')
        self.VistA.write('')
        self.VistA.wait('exit:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def checkin(self, vlist, mult=None):
        '''Checks a patient in'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('CI')
        if mult is not None:
            self.VistA.wait('Appointment')
            self.VistA.write(mult)
        for vitem in vlist:
            self.VistA.wait(vitem)
        self.VistA.write('')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def checkout(self, vlist1, vlist2, icd, mult=None):
        '''Checks a Patient out'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('CO')
        if mult is not None:
            self.VistA.wait('Appointment')
            self.VistA.write(mult)
        for vitem in vlist1:
            self.VistA.wait(vitem)
        self.VistA.wait('appointment')
        self.VistA.write('No')
        self.VistA.wait('date and time:')
        self.VistA.write('Now')
        self.VistA.wait('PROVIDER:')
        self.VistA.write('Alexander')
        self.VistA.wait('ENCOUNTER?')
        self.VistA.write('Yes')
        self.VistA.wait('PROVIDER')
        self.VistA.write('')
        self.VistA.wait('Diagnosis')
        self.VistA.write(icd)
        self.VistA.wait('Ok?')
        self.VistA.write('Yes')
        self.VistA.wait('ENCOUNTER?')
        self.VistA.write('Yes')
        self.VistA.wait('Resulting:')
        self.VistA.write('R')
        for vitem in vlist2:
            self.VistA.wait(vitem)
        self.VistA.wait('Diagnosis')
        self.VistA.write('')
        self.VistA.wait('Problem List?')
        self.VistA.write('No')
        self.VistA.wait('PROCEDURE')
        self.VistA.write('')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('screen?')
        self.VistA.write('No')
        self.VistA.wait('Clinic:')
        self.VistA.write('')

    def unschvisit(self, patient, patientname):
        '''Makes a walk-in appointment. Automatically checks in'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('UN')
        self.VistA.wait('Select Patient:')
        self.VistA.write(patient)
        self.VistA.wait('TIME:')
        self.VistA.write('')
        self.VistA.wait('TYPE:')
        self.VistA.write('Regular')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('Check Out:')
        self.VistA.write('CI')
        self.VistA.wait('CHECKED-IN:')
        self.VistA.write('')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('SLIP NOW?')
        self.VistA.write('No')
        self.VistA.wait(patientname)
        self.VistA.wait('Checked In')
        self.VistA.wait('Select Action')
        self.VistA.write('')

    def chgpatient(self, patient1, patient2, patientname1, patientname2):
        '''Changes the patient between patient 1 and patient 2'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('PT')
        self.VistA.wait('Patient:')
        self.VistA.write(patient1)
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait(patientname1.upper())
        self.VistA.wait('Select Action:')
        self.VistA.write('PT')
        self.VistA.wait('Patient:')
        self.VistA.write(patient2)
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait(patientname2.upper())
        self.VistA.wait('Select Action:')
        self.VistA.write('Quit')

    def chgclinic(self):
        '''Changes the clinic from clinic1 to clinic2'''
        self.VistA.wait('Clinic name:')
        self.VistA.write('Clinic1')
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Clinic1')
        self.VistA.wait('Select Action:')
        self.VistA.write('CL')
        self.VistA.wait('Select Clinic:')
        self.VistA.write('Clinic2')
        self.VistA.wait('Clinic2')
        self.VistA.wait('Select Action:')
        self.VistA.write('Quit')

    def chgdaterange(self):
        '''Changes the date range of the clinic'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait(self.getclinic())
        self.VistA.wait('Select Action:')
        self.VistA.write('CD')
        self.VistA.wait('Date:')
        self.VistA.write('t+7')
        self.VistA.wait('Date:')
        self.VistA.write('t+7')
        self.VistA.wait('Select Action:')
        self.VistA.write('CD')
        self.VistA.wait('Date:')
        self.VistA.write('t')
        self.VistA.wait('Date:')
        self.VistA.write('t')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def expandentry(self, vlist1, vlist2, vlist3, vlist4, vlist5, mult=None):
        '''Expands an appointment entry for more detail'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait(self.getclinic())
        self.VistA.wait('Select Action:')
        self.VistA.write('EP')
        if mult is not None:
            self.VistA.wait('Appointment')
            self.VistA.write(mult)
        for vitem in vlist1:
            self.VistA.wait(vitem)
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        for vitem in vlist2:
            self.VistA.wait(vitem)
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        for vitem in vlist3:
            self.VistA.wait(vitem)
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        for vitem in vlist4:
            self.VistA.wait(vitem)
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        for vitem in vlist5:
            self.VistA.wait(vitem)
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def addedit(self, name, icd):
        '''Functional but not complete. Exercises the Add/Edit menu but doesn't make any changes
        Same problem as checkout with the CPT codes and the MPI'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait(self.getclinic())
        self.VistA.wait('Select Action:')
        self.VistA.write('AE')
        self.VistA.wait('Name:')
        self.VistA.write(name)
        self.VistA.wait('exit:')
        self.VistA.write('A')
        self.VistA.wait('Clinic:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('Time:')
        time = self.schtime()
        self.VistA.write(time)
        self.VistA.wait('APPOINTMENT TYPE:')
        self.VistA.write('')
        self.VistA.wait('PROVIDER:')
        self.VistA.write('Alexander')
        self.VistA.wait('ENCOUNTER?')
        self.VistA.write('Yes')
        self.VistA.wait('Enter PROVIDER:')
        self.VistA.write('')
        self.VistA.wait('Diagnosis')
        self.VistA.write(icd)
        self.VistA.wait('Ok?')
        self.VistA.write('Yes')
        self.VistA.wait('ENCOUNTER?')
        self.VistA.write('Yes')
        self.VistA.wait('Resulting')
        self.VistA.write('R')
        self.VistA.wait('Diagnosis')
        self.VistA.write('')
        self.VistA.wait('Problem List?')
        self.VistA.write('')
        self.VistA.wait('CPT CODE')
        self.VistA.write('')
        self.VistA.wait('encounter?')
        self.VistA.write('Yes')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def patdem(self, name, mult=None):
        '''This edits the patients demographic information'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait(self.getclinic())
        self.VistA.wait('Select Action:')
        self.VistA.write('PD')
        if mult is not None:
            self.VistA.wait('Appointment')
            self.VistA.write(mult)
        self.VistA.wait(name)
        self.VistA.wait('COUNTRY:')
        self.VistA.write('')
        self.VistA.wait('ADDRESS')
        self.VistA.write('')
        self.VistA.wait(':')
        self.VistA.write('')
        self.VistA.wait('PHONE NUMBER')
        self.VistA.write('')
        self.VistA.wait('PHONE NUMBER')
        self.VistA.write('')
        self.VistA.wait('INDICATOR:')
        self.VistA.write('')
        self.VistA.wait('changes?')
        self.VistA.write('No')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('SEX:')
        self.VistA.write('')
        self.VistA.wait('INFORMATION')
        self.VistA.write('N')
        self.VistA.wait('INFORMATION:')
        self.VistA.write('W')
        self.VistA.wait('RACE INFORMATION')
        self.VistA.write('Yes')
        self.VistA.wait('INFORMATION:')
        self.VistA.write('')
        self.VistA.wait('STATUS:')
        self.VistA.write('Married')
        self.VistA.wait('PREFERENCE:')
        self.VistA.write('')
        self.VistA.wait('ACTIVE?')
        self.VistA.write('No')
        self.VistA.wait('NUMBER')
        self.VistA.write('')
        self.VistA.wait('NUMBER')
        self.VistA.write('')
        self.VistA.wait('ADDRESS:')
        self.VistA.write('')
        self.VistA.wait('Select Action')
        self.VistA.write('')

    def teaminfo(self, patient=None):
        '''This checks the display team info feature'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('TI')
        if patient is not None:
            self.VistA.wait('Select Patient')
            self.VistA.write(patient)
        self.VistA.wait('Team Information')
        self.VistA.wait('Select Action:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')

    def enroll(self, patient):
        '''This enrolls a patient as an inpatient in a clinic'''
        self.VistA.wait('OPTION NAME')
        self.VistA.write('Appointment Menu')
        self.VistA.wait('Menu Option')
        self.VistA.write('Edit Clinic Enrollment Data')
        self.VistA.wait('PATIENT NAME')
        self.VistA.write(patient)
        self.VistA.wait('CLINIC:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('ENROLLMENT CLINIC')
        self.VistA.write('Yes')
        self.VistA.wait('ENROLLMENT:')
        self.VistA.write('t')
        self.VistA.wait('DATE OF ENROLLMENT')
        self.VistA.write('Yes')
        self.VistA.wait('AC:')
        self.VistA.write('OPT')
        self.VistA.wait('DATE:')
        self.VistA.write('')
        self.VistA.wait('DISCHARGE:')
        self.VistA.write('')
        self.VistA.wait('DISCHARGE')
        self.VistA.write('')
        self.VistA.wait('CLINIC:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('ENROLLMENT')
        self.VistA.write('')
        self.VistA.wait('ENROLLMENT')
        self.VistA.write('')
        self.VistA.wait('AC:')
        self.VistA.write('')
        self.VistA.wait('DATE:')
        self.VistA.write('')
        self.VistA.wait('DISCHARGE')
        self.VistA.write('')
        self.VistA.wait('DISCHARGE')
        self.VistA.write('')
        self.VistA.wait('CLINIC')
        self.VistA.write('')
        self.VistA.wait('NAME:')
        self.VistA.write('')
        self.VistA.wait('Menu Option:')
        self.VistA.write('')
        self.VistA.wait('halt')
        self.VistA.write('')

    def discharge(self, patient, appnum=None):
        '''Discharges a patient from the clinic'''
        self.VistA.wait('Clinic name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('DC')
        if appnum is not None:
            self.VistA.wait('Select Appointment')
            self.VistA.write(appnum)
        self.VistA.wait('Discharging patient from')
        self.VistA.wait('DATE OF DISCHARGE:')
        self.VistA.write('t')
        self.VistA.wait('REASON FOR DISCHARGE')
        self.VistA.write('testing')
        self.VistA.wait('Action:')
        self.VistA.write('')

    def deletecheckout(self, appnum=None):
        '''Deletes checkout from the menu
        Must be signed in as fakedoc1 (1Doc!@#$)
        Must have the SD SUPERVISOR Key assigned to Dr. Alexander'''
        self.VistA.wait('Menu Option:')
        self.VistA.write('Appointment Menu')
        self.VistA.wait('Menu Option:')
        self.VistA.write('Appointment Management')
        self.VistA.wait('Clinic name')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Date:')
        self.VistA.write('')
        self.VistA.wait('Action:')
        self.VistA.write('DE')
        if appnum is not None:
            self.VistA.wait('Select Appointment')
            self.VistA.write(appnum)
        self.VistA.wait('check out?')
        self.VistA.write('Yes')
        self.VistA.wait('deleting')
        self.VistA.wait('continue:')
        self.VistA.write('')
        self.VistA.wait('deleting check out')
        self.VistA.wait('exit:')
        self.VistA.write('')
        self.VistA.wait('Action:')
        self.VistA.write('')

    def waitlistentry(self, patient):
        '''Enters a patient into the wait list
        This assumes that SDWL PARAMETER and SDWL MENU
        keys are given to fakedoc1'''
        self.VistA.wait('Option:')
        self.VistA.write('Appointment Menu')
        self.VistA.wait('Option:')
        self.VistA.write('Appointment Management')
        self.VistA.wait('name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('')
        for x in range(0, 2):
            self.VistA.wait('Date:')
            self.VistA.write('')
        self.VistA.wait('Action:')
        self.VistA.write('WE')
        self.VistA.wait('NAME:')
        self.VistA.write(patient)
        self.VistA.wait('Patient?')
        self.VistA.write('Yes')
        self.VistA.wait('response:')
        #TODO: Explore all three options (PCMM TEAM ASSIGNMENT, SERVICE/SPECIALTY, SPECIFIC CLINIC
        self.VistA.write('1')
        self.VistA.wait('Institution:')
        self.VistA.write('1327')
        self.VistA.wait('OK?')
        self.VistA.write('Yes')
        self.VistA.wait('Team:')
        self.VistA.write('1')
        self.VistA.wait('OK?')
        self.VistA.write('yes')
        self.VistA.wait('Comments:')
        self.VistA.write('test')
        self.VistA.wait('Action:')
        self.VistA.write('')

    def waitlistdisposition(self, patient):
        '''This verifies that the wait list disposition option is working'''
        self.VistA.wait('Option:')
        self.VistA.write('Appointment Management')
        self.VistA.wait('name:')
        self.VistA.write(self.getclinic())
        self.VistA.wait('OK?')
        self.VistA.write('')
        for x in range(0, 2):
            self.VistA.wait('Date:')
            self.VistA.write('')
        self.VistA.wait('Action:')
        self.VistA.write('WD')
        self.VistA.wait('PATIENT:')
        self.VistA.write(patient)
        self.VistA.wait('Quit?')
        self.VistA.write('Yes')
        #TODO: For deeper coverage, execute all 6 disposition reasons
        self.VistA.wait('response:')
        self.VistA.write('D')
        self.VistA.wait('removed from Wait List')
        self.VistA.wait('exit:')
        self.VistA.write('')
        self.VistA.wait('no Wait List')
        self.VistA.write('')
        self.VistA.wait('Select Action:')
        self.VistA.write('')
