// Although this unit has been autogenerated, it is intended to be modified.
// Source uSpecialAuthorityTypes, Date: 6/21/2024 10:08:06 AM

unit uSpecialAuthorityTypesEx;

{$RTTI EXPLICIT METHODS([vcProtected, vcPublic, vcPublished])}

interface

uses
  System.Generics.Collections,
  System.JSON,
  System.JSON.Serializers,
  uSpecialAuthorityTypes;

type
  TSpecialAuthorityValue = (savUnanswered, savNo, savYes);
  TSpecialAuthorityAction = (saaNone, saaSetNo, saaSetYes, saaSetUnanswered,
    saaDisable, saaEnable);
  TSpecialAuthorityActions = set of TSpecialAuthorityAction;

  TValueChangeActionEx = class(TValueChangeAction)
  private
    FRelatedActions: TSpecialAuthorityActions;
    FRelatedValue: TSpecialAuthorityValue;
    procedure ActionsNotify(Sender: TObject; const Item: string;
      AAction: TCollectionNotification);
    function GetWhenValueIs: string;
    procedure SetWhenValueIs(const Value: string);
  public
    constructor Create;
    property RelatedActions: TSpecialAuthorityActions read FRelatedActions;
    property RelatedValue: TSpecialAuthorityValue read FRelatedValue;
    property whenValueIs: string read GetWhenValueIs write SetWhenValueIs;
  end;

  TSpecialAuthorityTypeEx = class(TSpecialAuthorityType)
  private
    FValueChangeActionsEx: TObjectList<TValueChangeActionEx>;
    function GetDefaultValue: TSpecialAuthorityValue;
    function GetDescription: string;
    function GetDisplayText: string;
    procedure SetDescription(const Value: string);
  public
    constructor Create;
    destructor Destroy; override;
    property DefaultValue: TSpecialAuthorityValue read GetDefaultValue;
    property Description: string read GetDescription write SetDescription;
    property DisplayText: string read GetDisplayText;
    property ValueChangeActions: TObjectList<TValueChangeActionEx>
      read FValueChangeActionsEx;
  end;

  TSpecialAuthorityTypesEx = class(TSpecialAuthorityTypes)
  private
    FSpecialAuthorityTypesEx: TObjectList<TSpecialAuthorityTypeEx>;
    function GetCount: Integer;
    function GetItem(ACode: string): TSpecialAuthorityTypeEx; overload;
    function GetItem(Index: Integer): TSpecialAuthorityTypeEx; overload;
  public
    constructor Create;
    destructor Destroy; override;
    property Count: Integer read GetCount;
    property Item[ACode: string]: TSpecialAuthorityTypeEx read GetItem; default;
    property Item[Index: Integer]: TSpecialAuthorityTypeEx
      read GetItem; default;
    property SpecialAuthorityTypes: TObjectList<TSpecialAuthorityTypeEx>
      read FSpecialAuthorityTypesEx;
  end;

  TSpecialAuthorityTypesExConverter = class(TObject)
  private
    class function InternalToObject<T, U: class>(JSONValue: TJSONValue;
      JSONString: string; AOwner: U): T;
    class function LibraryName: string;
  public
    class function ToJSON<T>(AObject: T): string;
    class function ToObject<T, U: class>(JSON: TJSONValue; AOwner: U)
      : T; overload;
    class function ToObject<T, U: class>(JSON: string; AOwner: U): T; overload;
    class function ToObject<T: class>(JSON: string): T; overload;
    class function ToObject<T: class>(JSON: TJSONValue): T; overload;
  end;

var
  SpecialAuthorityTypesEx: TSpecialAuthorityTypesEx;

implementation

uses
  System.SysUtils,
  System.JSON.Converters,
  System.JSON.Writers,
  System.JSON.Readers,
  System.Rtti,
  System.TypInfo,
  Vcl.Menus,
  VAShared.RttiUtils,
  uMisc;

var
  SpecialAuthorityTypesExJSONLibrary: string;
  SpecialAuthorityTypesExJSONSerializerRegistered: Boolean = False;

procedure FreeAndNilOld(ATypeInf: PTypeInfo; Instance: TObject;
  FieldName: string);
var
  LField: TRttiField;
begin
  LField := TRttiUtils.GetRttiField(ATypeInf, FieldName);
  if Assigned(LField) then
  begin
    LField.GetValue(Instance).AsObject.Free;
    LField.SetValue(Instance, nil);
  end;
end;

{ TValueChangeActionEx }

procedure TValueChangeActionEx.ActionsNotify(Sender: TObject;
  const Item: string; AAction: TCollectionNotification);
var
  LinkedAction: TSpecialAuthorityAction;
begin
  LinkedAction := TMisc.GetEnumValueFromString<TSpecialAuthorityAction>
    (Item, 'saa');
  if LinkedAction <> saaNone then
    case AAction of
      cnAdded:
        Include(FRelatedActions, LinkedAction);
      cnExtracted, cnRemoved:
        Exclude(FRelatedActions, LinkedAction);
    end;
end;

constructor TValueChangeActionEx.Create;
begin
  inherited Create;
  actions.OnNotify := ActionsNotify;
end;

function TValueChangeActionEx.GetWhenValueIs: string;
begin
  Result := inherited whenValueIs;
end;

procedure TValueChangeActionEx.SetWhenValueIs(const Value: string);
begin
  inherited whenValueIs := Value;
  FRelatedValue := TMisc.GetEnumValueFromString<TSpecialAuthorityValue>
    (Value, 'sav');
end;

{ TSpecialAuthorityTypeEx }

constructor TSpecialAuthorityTypeEx.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TObjectList<TValueChangeAction>), Self,
    'FValueChangeActions');
  FValueChangeActionsEx := TObjectList<TValueChangeActionEx>.Create(True);
end;

destructor TSpecialAuthorityTypeEx.Destroy;
begin
  FreeAndNil(FValueChangeActionsEx);
  inherited;
end;

function TSpecialAuthorityTypeEx.GetDefaultValue: TSpecialAuthorityValue;
begin
  Result := TMisc.GetEnumValueFromString<TSpecialAuthorityValue>
    (default, 'sav');
end;

function TSpecialAuthorityTypeEx.GetDescription: string;
begin
  Result := inherited Description;
end;

function TSpecialAuthorityTypeEx.GetDisplayText: string;
begin
  Result := StripHotKey(inherited displayName);
end;

procedure TSpecialAuthorityTypeEx.SetDescription(const Value: string);
begin
  inherited Description := Trim(Value);
end;

{ TSpecialAuthorityTypesEx }

constructor TSpecialAuthorityTypesEx.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TObjectList<TSpecialAuthorityType>), Self,
    'FSpecialAuthorityTypes');
  FSpecialAuthorityTypesEx := TObjectList<TSpecialAuthorityTypeEx>.Create(True);
end;

destructor TSpecialAuthorityTypesEx.Destroy;
begin
  FreeAndNil(FSpecialAuthorityTypesEx);
  inherited;
end;

function TSpecialAuthorityTypesEx.GetCount: Integer;
begin
  Result := SpecialAuthorityTypes.Count;
end;

function TSpecialAuthorityTypesEx.GetItem(ACode: string)
  : TSpecialAuthorityTypeEx;
begin
  for var i := 0 to SpecialAuthorityTypes.Count - 1 do
    if SpecialAuthorityTypes[i].Code = ACode then
      Exit(SpecialAuthorityTypes[i]);
  Result := nil;
end;

function TSpecialAuthorityTypesEx.GetItem(Index: Integer)
  : TSpecialAuthorityTypeEx;
begin
  Result := SpecialAuthorityTypes[Index];
end;

{ TSpecialAuthorityTypesExConverter }

class function TSpecialAuthorityTypesExConverter.InternalToObject<T, U>
  (JSONValue: TJSONValue; JSONString: string; AOwner: U): T;
var
  Ctx: TRttiContext;
  LArgs: array of TValue;
  LMethod: TRttiMethod;
  LType: TRttiType;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  if Assigned(JSONValue) then
    Result := TJSONMapper<T>.Default.FromObject(JSONValue)
  else
    Result := TJSONMapper<T>.Default.FromObject(JSONString);
  Ctx := TRttiContext.Create;
  try
    LType := Ctx.GetType(Result.ClassInfo);
    for LMethod in LType.GetMethods do
      if Assigned(LMethod) and LMethod.HasName('PopulateOwner') then
      begin
        if Length(LMethod.GetParameters) > 0 then
        begin
          SetLength(LArgs, 1);
          LArgs[0] := TValue.From<U>(AOwner);
        end;
        LMethod.Invoke(Result, LArgs);
        Exit;
      end;
  finally
    Ctx.Free;
  end;
end;

class function TSpecialAuthorityTypesExConverter.LibraryName: string;
begin
  Result := QualifiedClassName;
  if Result.EndsWith('.' + ClassName) then
    delete(Result, Length(QualifiedClassName) - Length(ClassName) - 1, MaxInt);
end;

class function TSpecialAuthorityTypesExConverter.ToJSON<T>(AObject: T): string;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  Result := TJSONMapper<T>.Default.ToString(AObject);
end;

class function TSpecialAuthorityTypesExConverter.ToObject<T, U>
  (JSON: TJSONValue; AOwner: U): T;
begin
  Result := InternalToObject<T, U>(JSON, '', AOwner);
end;

class function TSpecialAuthorityTypesExConverter.ToObject<T, U>(JSON: string;
  AOwner: U): T;
begin
  Result := InternalToObject<T, U>(nil, JSON, AOwner);
end;

class function TSpecialAuthorityTypesExConverter.ToObject<T>(JSON: string): T;
begin
  Result := InternalToObject<T, TObject>(nil, JSON, nil);
end;

class function TSpecialAuthorityTypesExConverter.ToObject<T>
  (JSON: TJSONValue): T;
begin
  Result := InternalToObject<T, TObject>(JSON, '', nil);
end;

type
  TJsonListConverterValueChangeActionEx = class
    (TJsonTypedListConverter<TValueChangeActionEx>);
  TJsonListConverterSpecialAuthorityTypeEx = class
    (TJsonTypedListConverter<TSpecialAuthorityTypeEx>);

  TSpecialAuthorityTypesExJSONSerializer = class(TJsonSerializer)
  public
    constructor Create;
  end;

  { TSpecialAuthorityTypesExJSONSerializer }

constructor TSpecialAuthorityTypesExJSONSerializer.Create;
var
  AAttributes: TJsonDynamicAttributes;
  AFieldType: TRttiType;
  AResolver: TJsonDynamicContractResolver;
  Ctx: TRttiContext;

  procedure Init;
  var
    LField: TRttiField;
  begin
    AResolver := TJsonDynamicContractResolver.Create
      (TJsonMemberSerialization.Public);
    ContractResolver := AResolver;
    LField := TRttiUtils.GetRttiField(TypeInfo(TJsonDynamicContractResolver),
      'FDynamicAttributes');
    if Assigned(LField) then
      AAttributes := LField.GetValue(AResolver).AsType<TJsonDynamicAttributes>
    else
      AAttributes := nil;
    AFieldType := Ctx.GetType(TRttiType);
  end;

  procedure IgnoreProperties(AClass: TClass; ATypeInf: PTypeInfo);
  var
    i, J: Integer;
    LProp: TRttiProperty;
    LType: TRttiType;
    PropList: TArray<string>;
  begin
    LType := Ctx.GetType(ATypeInf);
    for LProp in LType.GetProperties do
    begin
      if LProp.HasAttribute<JsonInAttribute> then
        continue;
      if (not(LProp.Visibility in [mvPublic, mvPublished])) or
        (LProp.Parent.Name <> AClass.ClassName) then
      begin
        SetLength(PropList, Length(PropList) + 1);
        PropList[Length(PropList) - 1] := LProp.Name;
      end;
    end;
    for i := Length(PropList) - 1 downto 0 do
      for LProp in LType.GetProperties do
        if (CompareText(PropList[i], LProp.Name) = 0) and
          (LProp.Parent.Name = AClass.ClassName) then
        begin
          AResolver.SetPropertyName(ATypeInf, PropList[i], LProp.Name);
          for J := i to Length(PropList) - 2 do
            PropList[J] := PropList[J + 1];
          SetLength(PropList, Length(PropList) - 1);
          AAttributes.AddAttribute(LProp, JsonIgnoreAttribute.Create);
          break;
        end;
    AResolver.SetPropertiesIgnored(ATypeInf, PropList);
  end;

begin
  inherited Create;
  Ctx := TRttiContext.Create;
  try
    Init;
    IgnoreProperties(TValueChangeAction, TypeInfo(TValueChangeActionEx));
    IgnoreProperties(TSpecialAuthorityType, TypeInfo(TSpecialAuthorityTypeEx));
    IgnoreProperties(TSpecialAuthorityTypes,
      TypeInfo(TSpecialAuthorityTypesEx));
    AResolver.SetPropertyConverter(TypeInfo(TSpecialAuthorityTypeEx),
      'ValueChangeActions', TJsonListConverterValueChangeActionEx);
    AResolver.SetPropertyConverter(TypeInfo(TSpecialAuthorityTypesEx),
      'SpecialAuthorityTypes', TJsonListConverterSpecialAuthorityTypeEx);
  finally
    Ctx.Free;
  end;
end;

initialization

SpecialAuthorityTypesExJSONLibrary :=
  TSpecialAuthorityTypesExConverter.LibraryName;
SpecialAuthorityTypesExJSONSerializerRegistered :=
  TJSONMappers.RegisterLibrary(SpecialAuthorityTypesExJSONLibrary,
  TJSONMappers.TOptionality.DontCare, TJSONMappers.TOptionality.DontCare,
  TJSONMappers.TOptionality.DontCare,
  procedure(const AName: string; const ASerItems: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  const
    CSerItems: array [TJSONMappers.TItem] of string = ('Public', 'Fields');
  begin
    AIntro := '[JsonSerialize(TJsonMemberSerialization.' + CSerItems
      [ASerItems] + ')]';
    AReqUnit := SpecialAuthorityTypesExJSONLibrary;
  end,
  procedure(const AName, AOrigName: string; const AElem: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  begin
    if AnsiSameText(AName, AOrigName) and (AElem <> TJSONMappers.TItem.Field)
    then
      Exit;
    AIntro := '[JsonName(''' + AOrigName + ''')]';
    AReqUnit := SpecialAuthorityTypesExJSONLibrary;
  end,
  procedure(const AItemType: string; var AIntro, AReqUnit,
    AInstantiation: string)
  begin
    var
    LConv := StringReplace(AItemType, '<', '', [TReplaceFlag.rfReplaceAll]);
    LConv := 'TJsonListConverter' + StringReplace(LConv, '>', '',
      [TReplaceFlag.rfReplaceAll]);
    AIntro := '[JsonConverter(' + LConv + ')]';
    AReqUnit := SpecialAuthorityTypesExJSONLibrary;
    AInstantiation := LConv + ' = class(TJsonListConverter<' + AItemType + '>)';
  end,
  function(ApValue: Pointer; ApTypeInfo: PTypeInfo): TJSONObject
  var
    LSer: TSpecialAuthorityTypesExJSONSerializer;
    LWrt: TJsonObjectWriter;
    V: TValue;
  begin
    LSer := TSpecialAuthorityTypesExJSONSerializer.Create;
    LWrt := TJsonObjectWriter.Create(False);
    try
      TValue.Make(ApValue, ApTypeInfo, V);
      LSer.Serialize(LWrt, V);
      Result := LWrt.JSON as TJSONObject;
    finally
      LWrt.Free;
      LSer.Free;
    end;
  end,
  function(AValue: TJSONObject; ApTypeInfo: PTypeInfo): TValue
  var
    LSer: TSpecialAuthorityTypesExJSONSerializer;
    LRdr: TJsonObjectReader;
  begin
    LSer := TSpecialAuthorityTypesExJSONSerializer.Create;
    LRdr := TJsonObjectReader.Create(AValue);
    try
      Result := LSer.Deserialize(LRdr, ApTypeInfo);
    finally
      LRdr.Free;
      LSer.Free;
    end;
  end);

finalization

FreeAndNil(SpecialAuthorityTypesEx);
if SpecialAuthorityTypesExJSONSerializerRegistered then
  TJSONMappers.UnRegisterLibrary(SpecialAuthorityTypesExJSONLibrary);

end.
