// This unit is autogenerated. Do not edit it manually.
// Source: C:\Jeremy\GitHub\CPRSv33con\CPRS-chart\SpecialAuthority\PXSPECAUTH SPECAUTHSTRUCT.json
// Date: 8/28/2024 10:47:36 AM

unit uSpecialAuthorityTypes;

interface

uses
  System.Classes, System.JSON.Serializers, System.Generics.Collections, System.JSON.Converters;

type
  TPackage = class;
  TValueChangeAction = class;
  TSpecialAuthorityType = class;

  TJsonListConverterstring = class(TJsonTypedListConverter<string>);
  TJsonListConverterTPackage = class(TJsonTypedListConverter<TPackage>);
  TJsonListConverterTValueChangeAction = class(TJsonTypedListConverter<TValueChangeAction>);
  TJsonListConverterTSpecialAuthorityType = class(TJsonTypedListConverter<TSpecialAuthorityType>);

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TPackage = class(TPersistent)
  private
    Fexcluded: Boolean;
    Fname: string;
  public
    property excluded: Boolean read Fexcluded write Fexcluded;
    property name: string read Fname write Fname;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TValueChangeAction = class(TPersistent)
  private
    Factions: TList<string>;
    FlinkedSpecialAuthorities: TList<string>;
    FwhenValueIs: string;
  public
    constructor Create;
    destructor Destroy; override;
    [JsonConverter(TJsonListConverterstring)]
    property actions: TList<string> read Factions;
    [JsonConverter(TJsonListConverterstring)]
    property linkedSpecialAuthorities: TList<string> read FlinkedSpecialAuthorities;
    property whenValueIs: string read FwhenValueIs write FwhenValueIs;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TSpecialAuthorityType = class(TPersistent)
  private
    Fabbreviation: string;
    Fcode: string;
    Fdefault: string;
    Fdisabled: Boolean;
    FdisplayName: string;
    Fid: Integer;
    Fpackage: TObjectList<TPackage>;
    Fsequence: Integer;
    Fdescription: string;
    FvalueChangeActions: TObjectList<TValueChangeAction>;
  public
    constructor Create;
    destructor Destroy; override;
    property abbreviation: string read Fabbreviation write Fabbreviation;
    property code: string read Fcode write Fcode;
    property default: string read Fdefault write Fdefault;
    property disabled: Boolean read Fdisabled write Fdisabled;
    property displayName: string read FdisplayName write FdisplayName;
    property id: Integer read Fid write Fid;
    [JsonConverter(TJsonListConverterTPackage)]
    property package: TObjectList<TPackage> read Fpackage;
    property sequence: Integer read Fsequence write Fsequence;
    property description: string read Fdescription write Fdescription;
    [JsonConverter(TJsonListConverterTValueChangeAction)]
    property valueChangeActions: TObjectList<TValueChangeAction> read FvalueChangeActions;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TSpecialAuthorityTypes = class(TPersistent)
  private
    FspecialAuthorityTypes: TObjectList<TSpecialAuthorityType>;
  public
    constructor Create;
    destructor Destroy; override;
    [JsonConverter(TJsonListConverterTSpecialAuthorityType)]
    property specialAuthorityTypes: TObjectList<TSpecialAuthorityType> read FspecialAuthorityTypes;
  end;

implementation

uses
  System.SysUtils;

constructor TValueChangeAction.Create;
begin
  inherited Create;
  Factions := TList<string>.Create;
  FlinkedSpecialAuthorities := TList<string>.Create;
end;

destructor TValueChangeAction.Destroy;
begin
  FreeAndNil(Factions);
  FreeAndNil(FlinkedSpecialAuthorities);
  inherited Destroy;
end;

constructor TSpecialAuthorityType.Create;
begin
  inherited Create;
  Fpackage := TObjectList<TPackage>.Create(True);
  FvalueChangeActions := TObjectList<TValueChangeAction>.Create(True);
end;

destructor TSpecialAuthorityType.Destroy;
begin
  FreeAndNil(Fpackage);
  FreeAndNil(FvalueChangeActions);
  inherited Destroy;
end;

constructor TSpecialAuthorityTypes.Create;
begin
  inherited Create;
  FspecialAuthorityTypes := TObjectList<TSpecialAuthorityType>.Create(True);
end;

destructor TSpecialAuthorityTypes.Destroy;
begin
  FreeAndNil(FspecialAuthorityTypes);
  inherited Destroy;
end;

initialization

  RegisterClass(TPackage);
  RegisterClass(TValueChangeAction);
  RegisterClass(TSpecialAuthorityType);
  RegisterClass(TSpecialAuthorityTypes);

end.

