// Although this unit has been autogenerated, it is intended to be modified.
// Source uSpecialAuthority, Date: 6/21/2024 10:07:21 AM

unit uSpecialAuthorityEx;

{$RTTI EXPLICIT METHODS([vcProtected, vcPublic, vcPublished])}
{$TYPEINFO ON}

interface

uses
  System.Generics.Collections,
  System.JSON,
  System.JSON.Serializers,
  System.Classes,
  Vcl.Controls,
  Vcl.StdCtrls,
  VAShared.GenericStringList,
  ORCtrls,
  uSpecialAuthority,
  uSpecialAuthorityTypesEx;

type
  TSpecialAuthorityEx = class;
  TSpecialAuthoritiesEx = class;

  TSpecialAuthorityCheckBox = class(TORCheckBox)
  public type
    TCheckBoxType = (cbtYes, cbtNo, cbtBoth);
  private
    FCheckBoxType: TCheckBoxType;
    FInternalClick: Boolean;
    FLinkedCheckBox: TSpecialAuthorityCheckBox;
    FSpecialAuthorityEx: TSpecialAuthorityEx;
    FSpecialAuthorityValue: TSpecialAuthorityValue;
    procedure CMDialogChar(var Message: TCMDialogChar); message CM_DIALOGCHAR;
  protected
    procedure Click; override;
  public
    constructor Create(AOwner: TComponent;
      ASpecialAuthority: TSpecialAuthorityEx; ACheckBoxType: TCheckBoxType;
      ACustomHint: TCustomHint;
      ALinkedCheckBox: TSpecialAuthorityCheckBox = nil); reintroduce;
    destructor Destroy; override;
    property SpecialAuthorityEx: TSpecialAuthorityEx read FSpecialAuthorityEx;
    property SpecialAuthorityValue: TSpecialAuthorityValue
      read FSpecialAuthorityValue;
    property LinkedCheckBox: TSpecialAuthorityCheckBox read FLinkedCheckBox;
    property CheckBoxType: TCheckBoxType read FCheckBoxType;
  end;

  TSpecialAuthorityEx = class(TSpecialAuthority)
  private
    FCheckBoxBoth: TSpecialAuthorityCheckBox;
    FCheckBoxNo: TSpecialAuthorityCheckBox;
    FCheckBoxYes: TSpecialAuthorityCheckBox;
    FDesiredEnabled: Boolean;
    FEnabled: Boolean;
    FOwnerSpecialAuthoritiesEx: TSpecialAuthoritiesEx;
    FSpecialAuthorityTypeEx: TSpecialAuthorityTypeEx;
    FValue: TSpecialAuthorityValue;
    function GetCheckBox(cbType: TSpecialAuthorityCheckBox.TCheckBoxType)
      : TSpecialAuthorityCheckBox;
    function GetCode: string;
    function GetDefaultValue: TSpecialAuthorityValue;
    function GetStringValue: string;
    function GetVisible: Boolean;
    function GetYes: Boolean;
    function GetVisibleProperty: boolean;
    procedure SetCode(const Value: string);
    procedure SetEnabled(const Value: Boolean);
    procedure SetStringValue(const AValue: string);
    procedure SetValue(const AValue: TSpecialAuthorityValue);
    procedure SetVisible(const Value: Boolean);
    function GetValid: Boolean;
  protected
    procedure PopulateOwner(AOwner: TSpecialAuthoritiesEx);
  public
    constructor Create; virtual;
    destructor Destroy; override;
    procedure ClearExternalReferences; virtual;
    property CheckBox[cbType: TSpecialAuthorityCheckBox.TCheckBoxType]
      : TSpecialAuthorityCheckBox read GetCheckBox;
    property Code: string read GetCode write SetCode;
    property DefaultValue: TSpecialAuthorityValue read GetDefaultValue;
    property Enabled: Boolean read FDesiredEnabled write SetEnabled;
    property OwnerSpecialAuthoritiesEx: TSpecialAuthoritiesEx
      read FOwnerSpecialAuthoritiesEx;
    property SpecialAuthorityTypeEx: TSpecialAuthorityTypeEx
      read FSpecialAuthorityTypeEx;
    property StringValue: string read GetStringValue write SetStringValue;
    property Valid: Boolean read GetValid;
    property Value: TSpecialAuthorityValue read FValue write SetValue;
    property Visible: Boolean read GetVisible write SetVisible;
    property Yes: Boolean read GetYes;
    property isVisible: Boolean read GetVisibleProperty;
  end;

  TSpecialAuthorityClass = class of TSpecialAuthorityEx;
  TSpecialAuthorityCanEnableEvent = function(Sender: TSpecialAuthoritiesEx)
    : Boolean of object;

  TSpecialAuthoritiesEx = class(TSpecialAuthorities)
  private
    FApplyingValueChangeActions: Boolean;
    FOnCanEnableEvent: TSpecialAuthorityCanEnableEvent;
    FChanged: Boolean;
    FPackageLink: string;
    FSpecialAuthorityEx: TObjectList<TSpecialAuthorityEx>;
    FNewSpecialAuthorityClass: TSpecialAuthorityClass;
    FReloading: Boolean;
    function GetBoldText(ACode: string;
      ASpecialAuthoritiesEx: TSpecialAuthoritiesEx): Boolean;
    function GetCount: Integer;
    function GetHasUnanswered: Boolean;
    function GetItem(Index: Integer): TSpecialAuthorityEx; overload;
    function GetItem(ACode: string): TSpecialAuthorityEx; overload;
    function GetVisitStringText: string;
    procedure ReloadSpecialAuthorityTypes;
  protected
    function CanEnable: Boolean;
    procedure PopulateOwner;
  public const
    RelatedTo = 'Related to: ';
  public type
    TCopyType = (ctCopyValues, ctCopyVisible, ctCopyChanged, ctClearChanged);
    TCopyTypes = set of TCopyType;
  public
    constructor Create; overload;
    constructor Create(ANewSpecialAuthorityClass
      : TSpecialAuthorityClass); overload;
    destructor Destroy; override;
    procedure ApplyDefaults;
    procedure ApplyValueChangeActions;
    procedure Clear(ClearVisible: Boolean = False); virtual;
    procedure CopyFrom(Source: TSpecialAuthoritiesEx; ACopyTypes: TCopyTypes);
    procedure ChangeEnabled(AEnabled: Boolean);
    procedure ResetEnabled;
    property BoldText[ACode: string; ASpecialAuthoritys: TSpecialAuthoritiesEx]
      : Boolean read GetBoldText;
    property Changed: Boolean read FChanged write FChanged;
    property Count: Integer read GetCount;
    property HasUnanswered: Boolean read GetHasUnanswered;
    property Item[ACode: string]: TSpecialAuthorityEx read GetItem; default;
    property Item[Index: Integer]: TSpecialAuthorityEx read GetItem; default;
    property PackageLink: string read FPackageLink write FPackageLink;
    property SpecialAuthority: TObjectList<TSpecialAuthorityEx>
      read FSpecialAuthorityEx;
    property VisitStringText: string read GetVisitStringText;
    property OnCanEnableEvent: TSpecialAuthorityCanEnableEvent
      read FOnCanEnableEvent write FOnCanEnableEvent;
  end;

  TSpecialAuthoritiesExConverter = class(TObject)
  private
    class function InternalToObject<T, U: class>(JSONValue: TJSONValue;
      JSONString: string; AOwner: U): T;
    class function LibraryName: string;
  public
    class function ToJSON<T>(AObject: T): string;
    class function ToObject<T, U: class>(JSON: TJSONValue; AOwner: U)
      : T; overload;
    class function ToObject<T, U: class>(JSON: string; AOwner: U): T; overload;
    class function ToObject<T: class>(JSON: string): T; overload;
    class function ToObject<T: class>(JSON: TJSONValue): T; overload;
  end;

implementation

uses
  System.SysUtils,
  System.JSON.Converters,
  System.JSON.Writers,
  System.JSON.Readers,
  System.Rtti,
  System.TypInfo,
  System.Generics.Defaults,
  VAShared.RttiUtils,
  Vcl.Forms,
  uMisc,
  rSpecialAuthority;

var
  SpecialAuthoritiesExJSONLibrary: string;
  SpecialAuthoritiesExJSONSerializerRegistered: Boolean = False;

procedure FreeAndNilOld(ATypeInf: PTypeInfo; Instance: TObject;
  FieldName: string);
var
  LField: TRttiField;
begin
  LField := TRttiUtils.GetRttiField(ATypeInf, FieldName);
  if Assigned(LField) then
  begin
    LField.GetValue(Instance).AsObject.Free;
    LField.SetValue(Instance, nil);
  end;
end;

{ TSpecialAuthorityCheckBox }

procedure TSpecialAuthorityCheckBox.Click;
begin
  if not FInternalClick then
  begin
    FInternalClick := True;
    try
      if FCheckBoxType = cbtBoth then
      begin
        case State of
          cbUnchecked:
            FSpecialAuthorityEx.Value := savNo;
          cbChecked:
            FSpecialAuthorityEx.Value := savYes;
          cbGrayed:
            FSpecialAuthorityEx.Value := savUnanswered;
        end;
      end
      else if Checked then
      begin
        if Assigned(FLinkedCheckBox) then
          FLinkedCheckBox.Checked := False;
        FSpecialAuthorityEx.Value := FSpecialAuthorityValue;
      end
      else if (not Assigned(FLinkedCheckBox)) or (not FLinkedCheckBox.Checked)
      then
        FSpecialAuthorityEx.Value := savUnanswered;
      SpecialAuthorityEx.OwnerSpecialAuthoritiesEx.ApplyValueChangeActions;
    finally
      FInternalClick := False;
    end;
  end;
  inherited;
end;

type
  TCustomHintAccess = class(TCustomHint);

procedure TSpecialAuthorityCheckBox.CMDialogChar(var Message: TCMDialogChar);
begin
  if (FCheckBoxType <> cbtBoth) and IsAccel(Message.CharCode, Caption) then
  begin
    Message.Result := 1;
    if Assigned(CustomHint) then
      TCustomHintAccess(CustomHint).ShowHint(Self);
  end
  else
    inherited;
end;

constructor TSpecialAuthorityCheckBox.Create(AOwner: TComponent;
  ASpecialAuthority: TSpecialAuthorityEx; ACheckBoxType: TCheckBoxType;
  ACustomHint: TCustomHint; ALinkedCheckBox: TSpecialAuthorityCheckBox);
begin
  inherited Create(AOwner);
  if not Assigned(ASpecialAuthority) then
    raise EArgumentException.Create
      ('ASpecialAuthority argument required in TSpecialAuthorityCheckBox.Create');
  FSpecialAuthorityEx := ASpecialAuthority;
  FCheckBoxType := ACheckBoxType;
  Flat := True;
  case FCheckBoxType of
    cbtYes:
      begin
        FSpecialAuthorityValue := savYes;
        if Assigned(FSpecialAuthorityEx.FCheckBoxYes) then
          FreeAndNil(FSpecialAuthorityEx.FCheckBoxYes);
        FSpecialAuthorityEx.FCheckBoxYes := Self;
        Caption := '';
        Hint := FSpecialAuthorityEx.FSpecialAuthorityTypeEx.Description;
      end;
    cbtNo:
      begin
        FSpecialAuthorityValue := savNo;
        if Assigned(FSpecialAuthorityEx.FCheckBoxNo) then
          FreeAndNil(FSpecialAuthorityEx.FCheckBoxNo);
        FSpecialAuthorityEx.FCheckBoxNo := Self;
        Caption := ' ' + FSpecialAuthorityEx.SpecialAuthorityTypeEx.DisplayName;
        Hint := FSpecialAuthorityEx.FSpecialAuthorityTypeEx.Description;
      end;
    cbtBoth:
      begin
        AllowGrayed := True;
        if Assigned(FSpecialAuthorityEx.FCheckBoxBoth) then
          FreeAndNil(FSpecialAuthorityEx.FCheckBoxBoth);
        FSpecialAuthorityEx.FCheckBoxBoth := Self;
        Caption := '';
        Hint := FSpecialAuthorityEx.FSpecialAuthorityTypeEx.DisplayText
      end;
  end;
  if Assigned(ALinkedCheckBox) then
  begin
    FLinkedCheckBox := ALinkedCheckBox;
    ALinkedCheckBox.FLinkedCheckBox := Self;
  end;
  FInternalClick := True;
  try
    if (FCheckBoxType = cbtBoth) then
    begin
      FSpecialAuthorityEx.Value := FSpecialAuthorityEx.DefaultValue;
      if FSpecialAuthorityEx.Value = savUnanswered then
        FSpecialAuthorityEx.Value := FSpecialAuthorityEx.SpecialAuthorityTypeEx.
          DefaultValue;
      case FSpecialAuthorityEx.Value of
        savUnanswered:
          State := cbGrayed;
        savNo:
          State := cbUnchecked;
        savYes:
          State := cbChecked;
      end;
    end
    else if FSpecialAuthorityEx.Value = FSpecialAuthorityValue then
      Checked := True;
  finally
    FInternalClick := False;
  end;
  Enabled := FSpecialAuthorityEx.Enabled;
  ShowHint := True;
  if Assigned(ACustomHint) then
  begin
    CustomHint := ACustomHint;
    ParentCustomHint := True;
    Hint := '|' + Hint;
  end;
end;

destructor TSpecialAuthorityCheckBox.Destroy;
begin
  if Assigned(FSpecialAuthorityEx) then
  begin
    if FCheckBoxType = cbtBoth then
      FSpecialAuthorityEx.FCheckBoxBoth := nil
    else if FSpecialAuthorityValue = savYes then
      FSpecialAuthorityEx.FCheckBoxYes := nil
    else
      FSpecialAuthorityEx.FCheckBoxNo := nil;
  end;
  if Assigned(FLinkedCheckBox) then
    FLinkedCheckBox.FLinkedCheckBox := nil;
  inherited;
end;

{ TSpecialAuthorityEx }

const SpecialAuthorityValueStrings: array [TSpecialAuthorityValue]
    of string = ('', '0', '1');

procedure TSpecialAuthorityEx.ClearExternalReferences;
begin
  if Assigned(FCheckBoxYes) then
    FCheckBoxYes.FSpecialAuthorityEx := nil;
  if Assigned(FCheckBoxNo) then
    FCheckBoxNo.FSpecialAuthorityEx := nil;
  if Assigned(FCheckBoxBoth) then
    FCheckBoxBoth.FSpecialAuthorityEx := nil;
  FCheckBoxYes := nil;
  FCheckBoxNo := nil;
  FCheckBoxBoth := nil;
end;

constructor TSpecialAuthorityEx.Create;
begin
  inherited Create;
end;

destructor TSpecialAuthorityEx.Destroy;
begin
  ClearExternalReferences;
  inherited;
end;

function TSpecialAuthorityEx.GetCheckBox
  (cbType: TSpecialAuthorityCheckBox.TCheckBoxType): TSpecialAuthorityCheckBox;
begin
  case cbType of
    cbtYes:
      Result := FCheckBoxYes;
    cbtNo:
      Result := FCheckBoxNo;
    cbtBoth:
      Result := FCheckBoxBoth;
  else
    Result := nil;
  end;
end;

function TSpecialAuthorityEx.GetCode: string;
begin
  Result := inherited Code;
end;

function TSpecialAuthorityEx.GetDefaultValue: TSpecialAuthorityValue;
begin
  Result := TMisc.GetEnumValueFromString<TSpecialAuthorityValue>
    (default, 'sav');
end;

function TSpecialAuthorityEx.GetStringValue: string;
begin
  Result := SpecialAuthorityValueStrings[Value];
end;

function TSpecialAuthorityEx.GetValid: Boolean;
begin
//  Result := Assigned(FSpecialAuthorityTypeEx) and
//    (not FSpecialAuthorityTypeEx.disabled);
  Result := Assigned(FSpecialAuthorityTypeEx);
end;

function TSpecialAuthorityEx.GetVisible: Boolean;
begin
  if Valid then
  begin
    Result := inherited Visible;
    if Result and (FOwnerSpecialAuthoritiesEx.FPackageLink <> '') then
      for var I := 0 to FSpecialAuthorityTypeEx.package.Count - 1 do
        if FOwnerSpecialAuthoritiesEx.FPackageLink = FSpecialAuthorityTypeEx.
          package[I].name then
        begin
          Result := not FSpecialAuthorityTypeEx.package[I].excluded;
          break;
        end;
  end
  else
    Result := False;
end;

function TSpecialAuthorityEx.GetVisibleProperty: boolean;
begin
  result := inherited Visible;
end;

function TSpecialAuthorityEx.GetYes: Boolean;
begin
  Result := Visible and Enabled and (Value = savYes);
end;

procedure TSpecialAuthorityEx.PopulateOwner(AOwner: TSpecialAuthoritiesEx);
begin
  FOwnerSpecialAuthoritiesEx := AOwner;
end;

procedure TSpecialAuthorityEx.SetCode(const Value: string);
begin
  if inherited Code <> Value then
  begin
    inherited Code := Value;
    FSpecialAuthorityTypeEx := SpecialAuthorityTypesEx[Value];
  end;
end;

procedure TSpecialAuthorityEx.SetEnabled(const Value: Boolean);
begin
  FDesiredEnabled := Value;
  if (not Value) or ((FEnabled <> Value) and
    Assigned(FOwnerSpecialAuthoritiesEx) and
    FOwnerSpecialAuthoritiesEx.CanEnable) then
  begin
    FEnabled := Value;
    if Assigned(FCheckBoxYes) then
      FCheckBoxYes.Enabled := Value;
    if Assigned(FCheckBoxNo) then
      FCheckBoxNo.Enabled := Value;
    if Assigned(FCheckBoxBoth) then
      FCheckBoxBoth.Enabled := Value;
  end;
end;

procedure TSpecialAuthorityEx.SetStringValue(const AValue: string);
begin
  for var v := Low(TSpecialAuthorityValue) to High(TSpecialAuthorityValue) do
    if AValue = SpecialAuthorityValueStrings[v] then
    begin
      Value := v;
      Exit;
    end;
  Value := savUnanswered;
end;

procedure TSpecialAuthorityEx.SetValue(const AValue: TSpecialAuthorityValue);
begin
  if FValue <> AValue then
  begin
    if Valid then
      FValue := AValue
    else
      FValue := savUnanswered;
    FOwnerSpecialAuthoritiesEx.FChanged := True;
    if Assigned(FCheckBoxBoth) then
    begin
      case AValue of
        savUnanswered:
          FCheckBoxBoth.State := cbGrayed;
        savNo:
          FCheckBoxBoth.State := cbUnchecked;
        savYes:
          FCheckBoxBoth.State := cbChecked;
      end;
    end
    else if Assigned(FCheckBoxYes) and Assigned(FCheckBoxNo) then
      case FValue of
        savUnanswered:
          begin
            FCheckBoxYes.Checked := False;
            FCheckBoxNo.Checked := False;
          end;
        savNo:
          FCheckBoxNo.Checked := True;
        savYes:
          FCheckBoxYes.Checked := True;
      end;
  end;
end;

procedure TSpecialAuthorityEx.SetVisible(const Value: Boolean);
begin
  if inherited Visible <> Value then
  begin
    inherited Visible := Value;
    Enabled := Value;
  end;
end;

{ TSpecialAuthoritiesEx }

procedure TSpecialAuthoritiesEx.ApplyDefaults;
begin
  for var I := 0 to SpecialAuthority.Count - 1 do
    if SpecialAuthority[I].Valid and (SpecialAuthority[I].Value = savUnanswered)
    then
      SpecialAuthority[I].Value := SpecialAuthority[I]
        .SpecialAuthorityTypeEx.DefaultValue;
end;

procedure TSpecialAuthoritiesEx.ApplyValueChangeActions;
var
  Actions: TObjectList<TValueChangeActionEx>;
begin
  if FApplyingValueChangeActions then
    Exit;
  FApplyingValueChangeActions := True;
  try
    for var I := 0 to SpecialAuthority.Count - 1 do
    begin
      if not SpecialAuthority[I].Valid then
        continue;
      Actions := SpecialAuthority[I].SpecialAuthorityTypeEx.ValueChangeActions;
      for var j := 0 to Actions.Count - 1 do
        if SpecialAuthority[I].Value = Actions[j].RelatedValue then
          for var saa := Low(TSpecialAuthorityAction)
            to High(TSpecialAuthorityAction) do
            if saa in Actions[j].RelatedActions then
              for var k := 0 to Actions[j].linkedSpecialAuthorities.Count - 1 do
                case saa of
                  saaSetNo:
                    Item[Actions[j].linkedSpecialAuthorities[k]].Value := savNo;
                  saaSetYes:
                    Item[Actions[j].linkedSpecialAuthorities[k]].Value
                      := savYes;
                  saaSetUnanswered:
                    Item[Actions[j].linkedSpecialAuthorities[k]].Value :=
                      savUnanswered;
                  saaDisable:
                    Item[Actions[j].linkedSpecialAuthorities[k]]
                      .Enabled := False;
                  saaEnable:
                    Item[Actions[j].linkedSpecialAuthorities[k]]
                      .Enabled := True;
                end;
    end;
  finally
    FApplyingValueChangeActions := False;
  end;
end;

function TSpecialAuthoritiesEx.CanEnable: Boolean;
begin
  if Assigned(FOnCanEnableEvent) then
    Result := FOnCanEnableEvent(Self)
  else
    Result := True;
end;

procedure TSpecialAuthoritiesEx.ChangeEnabled(AEnabled: Boolean);
begin
  for var I := 0 to SpecialAuthority.Count - 1 do
    SpecialAuthority[I].Enabled := AEnabled;
end;

procedure TSpecialAuthoritiesEx.Clear(ClearVisible: Boolean);
begin
  for var I := 0 to SpecialAuthority.Count - 1 do
  begin
    SpecialAuthority[I].FValue := savUnanswered;
    if ClearVisible then
    begin
      SpecialAuthority[I].Visible := False;
      SpecialAuthority[I].Enabled := False;
      SpecialAuthority[I].default := '';
    end;
  end;
  FChanged := False;
end;

procedure TSpecialAuthoritiesEx.CopyFrom(Source: TSpecialAuthoritiesEx;
  ACopyTypes: TCopyTypes);
var
  sa1, sa2: TSpecialAuthorityEx;
begin
  if Assigned(Source) then
  begin
    for var I := 0 to Source.Count - 1 do
    begin
      sa1 := Source[I];
      sa2 := Item[sa1.Code];
      if ctCopyVisible in ACopyTypes then
      begin
        sa2.default := sa1.default;
        sa2.Visible := sa1.Visible;
        sa2.Enabled := sa1.Enabled;
      end;
      if ctCopyValues in ACopyTypes then
        sa2.FValue := sa1.FValue;
    end;
    if ctCopyChanged in ACopyTypes then
      FChanged := Source.FChanged
    else if ctClearChanged in ACopyTypes then
      FChanged := False;
  end;
end;

constructor TSpecialAuthoritiesEx.Create(ANewSpecialAuthorityClass
  : TSpecialAuthorityClass);
begin
  Create;
  FNewSpecialAuthorityClass := ANewSpecialAuthorityClass;
end;

constructor TSpecialAuthoritiesEx.Create;
begin
  inherited Create;
  FreeAndNilOld(TypeInfo(TObjectList<TSpecialAuthority>), Self,
    'FSpecialAuthority');
  FSpecialAuthorityEx := TObjectList<TSpecialAuthorityEx>.Create
    (TComparer<TSpecialAuthorityEx>.Construct(
    function(const Left, Right: TSpecialAuthorityEx): Integer
    begin
      if Left.Valid and Right.Valid then
        if Left.SpecialAuthorityTypeEx.Sequence < Right.SpecialAuthorityTypeEx.Sequence
        then
          Result := -1
        else
          Result := 1
      else
        Result := 0;
    end), True);
  FNewSpecialAuthorityClass := TSpecialAuthorityEx;
  FReloading := false;
end;

destructor TSpecialAuthoritiesEx.Destroy;
begin
  FreeAndNil(FSpecialAuthorityEx);
  inherited;
end;

function TSpecialAuthoritiesEx.GetBoldText(ACode: string;
ASpecialAuthoritiesEx: TSpecialAuthoritiesEx): Boolean;
begin
  Result := (Item[ACode].Yes and (not ASpecialAuthoritiesEx[ACode].Yes));
end;

function TSpecialAuthoritiesEx.GetCount: Integer;
begin
  Result := SpecialAuthority.Count;
end;

function TSpecialAuthoritiesEx.GetHasUnanswered: Boolean;
begin
  ApplyValueChangeActions;
  for var I := 0 to SpecialAuthority.Count - 1 do
    if SpecialAuthority[I].Visible and SpecialAuthority[I].Enabled and
      (SpecialAuthority[I].Value = savUnanswered) then
      Exit(True);
  Result := False;
end;

function TSpecialAuthoritiesEx.GetItem(Index: Integer): TSpecialAuthorityEx;
begin
  Result := SpecialAuthority[Index];
end;

function TSpecialAuthoritiesEx.GetItem(ACode: string): TSpecialAuthorityEx;
begin
  for var I := 0 to SpecialAuthority.Count - 1 do
    if SpecialAuthority[I].Code = ACode then
      Exit(SpecialAuthority[I]);
  if Assigned(SpecialAuthorityTypesEx[ACode]) then
  begin
    Result := FNewSpecialAuthorityClass.Create;
    Result.PopulateOwner(Self);
    Result.Code := ACode;
    Result.FValue := savUnanswered;
    Result.Visible := False;
    SpecialAuthority.Add(Result);
    SpecialAuthority.Sort;
    Exit;
  end;
  Result := nil;
end;

function TSpecialAuthoritiesEx.GetVisitStringText: string;
begin
  Result := '';
  for var I := 0 to SpecialAuthority.Count - 1 do
    if SpecialAuthority[I].Yes then
    begin
      if Result <> '' then
        Result := Result + ', ';
      Result := Result + SpecialAuthority[I].SpecialAuthorityTypeEx.DisplayText;
    end;
  if Result <> '' then
    Result := RelatedTo + Result;
end;

procedure TSpecialAuthoritiesEx.PopulateOwner;
begin
  for var I := 0 to FSpecialAuthorityEx.Count - 1 do
    FSpecialAuthorityEx[I].PopulateOwner(Self);
end;

procedure TSpecialAuthoritiesEx.ReloadSpecialAuthorityTypes;
var
i: integer;
Reload: boolean;
Error: string;
begin
  reload := false;
  if SpecialAuthority.Count <> SpecialAuthorityTypesEx.Count  then
    Reload := true
  else begin
    for i := 0 to SpecialAuthority.Count - 1 do
    begin
      if SpecialAuthorityTypesEx.Item[SpecialAuthority[i].Code] = nil then
      begin
        Reload := true;
        break;
      end
      else begin
        if (SpecialAuthorityTypesEx.Item[SpecialAuthority[i].Code].disabled) and
        (SpecialAuthority[i].isVisible) then
        begin
          Reload := true;
          break;
        end;
      end;
    end;
  end;
  if Reload then
  begin
    ReloadSpecialAuthorityTypesEx(Error);
    if Error = '' then FReloading := true;
  end;
end;

procedure TSpecialAuthoritiesEx.ResetEnabled;
begin
  for var I := 0 to Count - 1 do
    Item[I].Enabled := Item[I].FDesiredEnabled;
  ApplyValueChangeActions;
end;

{ TSpecialAuthoritiesExConverter }

class function TSpecialAuthoritiesExConverter.InternalToObject<T, U>
  (JSONValue: TJSONValue; JSONString: string; AOwner: U): T;
var
  Ctx: TRttiContext;
  LArgs: array of TValue;
  LMethod: TRttiMethod;
  LType: TRttiType;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  if Assigned(JSONValue) then
    Result := TJSONMapper<T>.default.FromObject(JSONValue)
  else
    Result := TJSONMapper<T>.default.FromObject(JSONString);
  if T = TSpecialAuthoritiesEx then
  begin
    (Result as TSpecialAuthoritiesEx).ReloadSpecialAuthorityTypes;
    if not (Result as TSpecialAuthoritiesEx).FReloading then
      (Result as TSpecialAuthoritiesEx).SpecialAuthority.Sort;
  end;
  Ctx := TRttiContext.Create;
  try
    LType := Ctx.GetType(Result.ClassInfo);
    for LMethod in LType.GetMethods do
      if Assigned(LMethod) and LMethod.HasName('PopulateOwner') then
      begin
        if Length(LMethod.GetParameters) > 0 then
        begin
          SetLength(LArgs, 1);
          LArgs[0] := TValue.From<U>(AOwner);
        end;
        LMethod.Invoke(Result, LArgs);
        Exit;
      end;
  finally
    Ctx.Free;
  end;
end;

class function TSpecialAuthoritiesExConverter.LibraryName: string;
begin
  Result := QualifiedClassName;
  if Result.EndsWith('.' + ClassName) then
    delete(Result, Length(QualifiedClassName) - Length(ClassName) - 1, MaxInt);
end;

class function TSpecialAuthoritiesExConverter.ToJSON<T>(AObject: T): string;
begin
  TJSONMapper<T>.SetDefaultLibrary(LibraryName);
  Result := TJSONMapper<T>.default.ToString(AObject);
end;

class function TSpecialAuthoritiesExConverter.ToObject<T, U>(JSON: TJSONValue;
AOwner: U): T;
begin
  Result := InternalToObject<T, U>(JSON, '', AOwner);
end;

class function TSpecialAuthoritiesExConverter.ToObject<T, U>(JSON: string;
AOwner: U): T;
begin
  Result := InternalToObject<T, U>(nil, JSON, AOwner);
end;

class function TSpecialAuthoritiesExConverter.ToObject<T>(JSON: string): T;
begin
  Result := InternalToObject<T, TObject>(nil, JSON, nil);
end;

class function TSpecialAuthoritiesExConverter.ToObject<T>(JSON: TJSONValue): T;
begin
  Result := InternalToObject<T, TObject>(JSON, '', nil);
end;

type
  TJsonListConverterSpecialAuthorityEx = class
    (TJsonTypedListConverter<TSpecialAuthorityEx>);

  TSpecialAuthoritiesExJSONSerializer = class(TJsonSerializer)
  public
    constructor Create;
  end;

  { TSpecialAuthoritiesExJSONSerializer }

constructor TSpecialAuthoritiesExJSONSerializer.Create;
var
  AAttributes: TJsonDynamicAttributes;
  AFieldType: TRttiType;
  AResolver: TJsonDynamicContractResolver;
  Ctx: TRttiContext;

  procedure Init;
  var
    LField: TRttiField;
  begin
    AResolver := TJsonDynamicContractResolver.Create
      (TJsonMemberSerialization.Public);
    ContractResolver := AResolver;
    LField := TRttiUtils.GetRttiField(TypeInfo(TJsonDynamicContractResolver),
      'FDynamicAttributes');
    if Assigned(LField) then
      AAttributes := LField.GetValue(AResolver).AsType<TJsonDynamicAttributes>
    else
      AAttributes := nil;
    AFieldType := Ctx.GetType(TRttiType);
  end;

  procedure IgnoreProperties(AClass: TClass; ATypeInf: PTypeInfo);
  var
    I, j: Integer;
    LProp: TRttiProperty;
    LType: TRttiType;
    PropList: TArray<string>;
  begin
    LType := Ctx.GetType(ATypeInf);
    for LProp in LType.GetProperties do
    begin
      if LProp.HasAttribute<JsonInAttribute> then
        continue;
      if (not(LProp.Visibility in [mvPublic, mvPublished])) or
        (LProp.Parent.name <> AClass.ClassName) then
      begin
        SetLength(PropList, Length(PropList) + 1);
        PropList[Length(PropList) - 1] := LProp.name;
      end;
    end;
    for I := Length(PropList) - 1 downto 0 do
      for LProp in LType.GetProperties do
        if (CompareText(PropList[I], LProp.name) = 0) and
          (LProp.Parent.name = AClass.ClassName) then
        begin
          AResolver.SetPropertyName(ATypeInf, PropList[I], LProp.name);
          for j := I to Length(PropList) - 2 do
            PropList[j] := PropList[j + 1];
          SetLength(PropList, Length(PropList) - 1);
          AAttributes.AddAttribute(LProp, JsonIgnoreAttribute.Create);
          break;
        end;
    AResolver.SetPropertiesIgnored(ATypeInf, PropList);
  end;

begin
  inherited Create;
  Ctx := TRttiContext.Create;
  try
    Init;
    IgnoreProperties(TSpecialAuthority, TypeInfo(TSpecialAuthorityEx));
    IgnoreProperties(TSpecialAuthorities, TypeInfo(TSpecialAuthoritiesEx));
    AResolver.SetPropertyConverter(TypeInfo(TSpecialAuthoritiesEx),
      'SpecialAuthority', TJsonListConverterSpecialAuthorityEx);
  finally
    Ctx.Free;
  end;
end;

initialization

SpecialAuthoritiesExJSONLibrary := TSpecialAuthoritiesExConverter.LibraryName;
SpecialAuthoritiesExJSONSerializerRegistered := TJSONMappers.RegisterLibrary
  (SpecialAuthoritiesExJSONLibrary, TJSONMappers.TOptionality.DontCare,
  TJSONMappers.TOptionality.DontCare, TJSONMappers.TOptionality.DontCare,
  procedure(const AName: string; const ASerItems: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  const
    CSerItems: array [TJSONMappers.TItem] of string = ('Public', 'Fields');
  begin
    AIntro := '[JsonSerialize(TJsonMemberSerialization.' + CSerItems
      [ASerItems] + ')]';
    AReqUnit := SpecialAuthoritiesExJSONLibrary;
  end,
  procedure(const AName, AOrigName: string; const AElem: TJSONMappers.TItem;
    var AIntro: string; var AReqUnit: string)
  begin
    if AnsiSameText(AName, AOrigName) and (AElem <> TJSONMappers.TItem.Field)
    then
      Exit;
    AIntro := '[JsonName(''' + AOrigName + ''')]';
    AReqUnit := SpecialAuthoritiesExJSONLibrary;
  end,
  procedure(const AItemType: string; var AIntro, AReqUnit,
    AInstantiation: string)
  begin
    var
    LConv := StringReplace(AItemType, '<', '', [TReplaceFlag.rfReplaceAll]);
    LConv := 'TJsonListConverter' + StringReplace(LConv, '>', '',
      [TReplaceFlag.rfReplaceAll]);
    AIntro := '[JsonConverter(' + LConv + ')]';
    AReqUnit := SpecialAuthoritiesExJSONLibrary;
    AInstantiation := LConv + ' = class(TJsonListConverter<' + AItemType + '>)';
  end,
  function(ApValue: Pointer; ApTypeInfo: PTypeInfo): TJSONObject
  var
    LSer: TSpecialAuthoritiesExJSONSerializer;
    LWrt: TJsonObjectWriter;
    v: TValue;
  begin
    LSer := TSpecialAuthoritiesExJSONSerializer.Create;
    LWrt := TJsonObjectWriter.Create(False);
    try
      TValue.Make(ApValue, ApTypeInfo, v);
      LSer.Serialize(LWrt, v);
      Result := LWrt.JSON as TJSONObject;
    finally
      LWrt.Free;
      LSer.Free;
    end;
  end,
  function(AValue: TJSONObject; ApTypeInfo: PTypeInfo): TValue
  var
    LSer: TSpecialAuthoritiesExJSONSerializer;
    LRdr: TJsonObjectReader;
  begin
    LSer := TSpecialAuthoritiesExJSONSerializer.Create;
    LRdr := TJsonObjectReader.Create(AValue);
    try
      Result := LSer.Deserialize(LRdr, ApTypeInfo);
    finally
      LRdr.Free;
      LSer.Free;
    end;
  end);

finalization

if SpecialAuthoritiesExJSONSerializerRegistered then
  TJSONMappers.UnRegisterLibrary(SpecialAuthoritiesExJSONLibrary);

end.
