// This unit is autogenerated. Do not edit it manually.
// Source: C:\Jeremy\GitHub\CPRSv33con\CPRS-chart\SpecialAuthority\INDSEL.json
// Date: 6/24/2024 3:28:20 PM

unit uSpecialAuthority;

interface

uses
  System.Classes, System.JSON.Serializers, System.Generics.Collections, System.JSON.Converters;

type
  TSpecialAuthority = class;

  TJsonListConverterTSpecialAuthority = class(TJsonTypedListConverter<TSpecialAuthority>);

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TSpecialAuthority = class(TPersistent)
  private
    Fcode: string;
    Fdefault: string;
    Fvisible: Boolean;
  public
    property code: string read Fcode write Fcode;
    property default: string read Fdefault write Fdefault;
    property visible: Boolean read Fvisible write Fvisible;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TSpecialAuthorities = class(TPersistent)
  private
    Ferror: string;
    FspecialAuthority: TObjectList<TSpecialAuthority>;
    Fsuccess: Boolean;
  public
    constructor Create;
    destructor Destroy; override;
    property error: string read Ferror write Ferror;
    [JsonConverter(TJsonListConverterTSpecialAuthority)]
    property specialAuthority: TObjectList<TSpecialAuthority> read FspecialAuthority;
    property success: Boolean read Fsuccess write Fsuccess;
  end;

implementation

uses
  System.SysUtils;

constructor TSpecialAuthorities.Create;
begin
  inherited Create;
  FspecialAuthority := TObjectList<TSpecialAuthority>.Create(True);
end;

destructor TSpecialAuthorities.Destroy;
begin
  FreeAndNil(FspecialAuthority);
  inherited Destroy;
end;

initialization

  RegisterClass(TSpecialAuthority);
  RegisterClass(TSpecialAuthorities);

end.
