# These settings are synced to GitHub by https://probot.github.io/apps/settings/

labels:
  - name: backlog
    color: ce7048
    description: To be addressed in a future sprint

  - name: bug
    color: d73a4a
    description: "A defect: something isn't working"

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: invalid
    color: e4e669
    description: This doesn't seem right

  - name: pm_approved
    color: f4eb30
    description: Approved by Product Manager

  - name: po_approved
    color: b5f95c
    description: Approved by Product Owner

  - name: question
    color: d876e3
    description: Further information is requested

  - name: severity 1 critical
    color: d73a4a
    description: Critical severity  bug

  - name: severity 2 high
    color: d73a4a
    description: High severity bug

  - name: severity 3 medium
    color: d73a4a
    description: Medium severity bug

  - name: severity 4 low
    color: d73a4a
    description: Low severity bug

  - name: task
    color: d4c5f9
    description: A small body of work related to a user story or bug

  - name: test
    color: c6f79b
    description: Automated test or manual test plan

  - name: wontfix
    color: ffffff
    description: This will not be worked on
