#!/bin/bash
#chkconfig: 2345 80 05
#description: init script for cache
# Scipt based on:
# http://training.intersystems.com/tutorials/DocBook.UI.Page.cls?KEY=GHA_redhat_clusters
# Edit the name of the Cache instance to be started into the shell
# variable below.
inst="prod"
basdir=`/usr/bin/ccontrol list $inst | grep -i directory: | awk {'print $2'}`
if [ "${basdir}" = "" ]
then
  echo "Instance $inst not found"
  exit 1
fi
type=$1
localnode=`uname -a | awk '{print $2}'`
# See how we were called. 
case "$type" in 
   
  (start)
        # Start daemons.
   if [ -e ${basdir}/mgr/cache.ids ]
   then
      echo "Cache already started"
      exit 1
   else
        # If there is no cache.ids file, it's just a normal startup.
      touch /var/lock/subsys/cacheprod
      failflag=""
   fi
   echo "Starting Ensemble instance $inst on $localnode"
   ccontrol start $inst quietly
   status=$?
   case $status in
   (1)
       echo "...Failed to start"
       exit 1
       ;;
   (0)
       echo "...Started"
       exit 0
   esac
       ;;
  (stop)
        # Stop daemons.
        echo "Stopping Ensemble instance $inst on $localnode"
   ccontrol stop $inst quietly
   rm -f /var/lock/subsys/cacheprod
   status=$?
   case $status in
   (1)
       echo "Ensemble instance $inst failed to stop"
       exit 1
       ;;
   (0)
       echo "Ensemble instance $inst stopped"
       exit 0
   esac
   ;;
  (status)
   FIELDWIDTH=2
   state=`/usr/bin/ccontrol all | grep -i $inst | awk {'print $1'}`
   if [ "$state" = "up" ]
   then
      echo "$inst is UP"
      exit 0   #cache is up
   fi
      echo "$inst is DOWN or unable to determine status"
      exit 1   #cache is down or we can't tell
        ;;
  (*)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac
  
exit 0
